// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: Lexer.flex

/* - - - - - - - - - - - - - - - - - CODIGO DE USUARIO - - - - - - - - - - - - - - - - - */
package com.jbrod.apptrivias.analizadores;
import java_cup.runtime.*;


@SuppressWarnings("fallthrough")
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\25\u0100\1\u0200\11\u0100\1\u0300\17\u0100\1\u0400\u10cf\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\1\1\3\22\0\1\4\1\5"+
    "\1\6\1\0\1\7\3\0\1\10\1\11\2\0\1\12"+
    "\1\13\1\14\1\0\1\15\1\16\10\17\1\20\1\0"+
    "\1\21\1\22\1\23\1\24\1\0\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\33\1\34\1\35\1\33\1\36"+
    "\1\37\1\40\1\41\1\42\1\43\1\33\1\44\1\45"+
    "\1\46\1\47\1\50\1\33\1\51\2\33\1\52\1\0"+
    "\1\53\1\0\1\54\1\0\1\55\3\33\1\56\3\33"+
    "\1\57\4\33\1\60\1\61\2\33\1\62\1\63\1\64"+
    "\1\33\1\65\1\33\1\66\2\33\1\67\1\70\1\71"+
    "\7\0\1\1\32\0\1\1\36\0\1\72\u01c0\0\1\1"+
    "\177\0\13\1\21\0\2\73\12\0\2\1\5\0\1\1"+
    "\57\0\1\1\240\0\1\1\377\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1280];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\11\5\1\16"+
    "\1\17\1\5\1\20\1\21\1\22\1\0\21\5\1\0"+
    "\24\5\1\0\17\5\1\23\4\5\1\0\4\5\1\24"+
    "\1\5\1\25\1\5\1\26\4\5\1\27\5\5\1\0"+
    "\7\5\1\30\1\31\3\5\1\32\1\33\1\34\1\0"+
    "\4\5\1\35\1\36\4\5\1\0\3\5\1\37\1\5"+
    "\1\40\2\5\1\0\2\5\1\41\1\42\1\43\1\5"+
    "\1\0\1\44\2\5\1\0\1\45\1\5\1\0\1\5"+
    "\1\0\1\46\11\0\1\47";

  private static int [] zzUnpackAction() {
    int [] result = new int[174];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\74\0\74\0\170\0\74\0\74\0\264\0\74"+
    "\0\74\0\74\0\360\0\74\0\u012c\0\74\0\74\0\u0168"+
    "\0\u01a4\0\u01e0\0\u021c\0\u0258\0\u0294\0\u02d0\0\u030c\0\u0348"+
    "\0\74\0\74\0\u0384\0\74\0\74\0\74\0\u03c0\0\u03fc"+
    "\0\u0438\0\u0474\0\u04b0\0\u04ec\0\u0528\0\u0564\0\u05a0\0\u05dc"+
    "\0\u0618\0\u0654\0\u0690\0\u06cc\0\u0708\0\u0744\0\u0780\0\u07bc"+
    "\0\u07f8\0\u0834\0\u0870\0\u08ac\0\u08e8\0\u0924\0\u0960\0\u099c"+
    "\0\u09d8\0\u0a14\0\u0a50\0\u0a8c\0\u0ac8\0\u0b04\0\u0b40\0\u0b7c"+
    "\0\u0bb8\0\u0bf4\0\u0c30\0\u0c6c\0\u0ca8\0\u0ce4\0\u0d20\0\u0d5c"+
    "\0\u0d98\0\u0dd4\0\u0e10\0\u0e4c\0\u0e88\0\u0ec4\0\u0f00\0\u0f3c"+
    "\0\u0f78\0\u0fb4\0\u0ff0\0\u102c\0\u1068\0\u01a4\0\u10a4\0\u10e0"+
    "\0\u111c\0\u1158\0\u1194\0\u11d0\0\u120c\0\u1248\0\u1284\0\u01a4"+
    "\0\u12c0\0\u01a4\0\u12fc\0\u01a4\0\u1338\0\u1374\0\u13b0\0\u13ec"+
    "\0\u01a4\0\u1428\0\u1464\0\u14a0\0\u14dc\0\u1518\0\u1554\0\u1590"+
    "\0\u15cc\0\u1608\0\u1644\0\u1680\0\u16bc\0\u16f8\0\u01a4\0\u01a4"+
    "\0\u1734\0\u1770\0\u17ac\0\u01a4\0\u01a4\0\u01a4\0\u17e8\0\u1824"+
    "\0\u1860\0\u189c\0\u18d8\0\u01a4\0\u01a4\0\u1914\0\u1950\0\u198c"+
    "\0\u19c8\0\u1a04\0\u1a40\0\u1a7c\0\u1ab8\0\u01a4\0\u1af4\0\u01a4"+
    "\0\u1b30\0\u1b6c\0\u1ba8\0\u1be4\0\u1c20\0\264\0\264\0\u01a4"+
    "\0\u1c5c\0\u1c98\0\264\0\u1cd4\0\u1d10\0\u1d4c\0\264\0\u1d88"+
    "\0\u1dc4\0\u1e00\0\u1e3c\0\264\0\u1e78\0\u1eb4\0\u1ef0\0\u1f2c"+
    "\0\u1f68\0\u1fa4\0\u1fe0\0\u201c\0\u2058\0\74";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[174];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\4\1\3\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\7\1\2\3\13\1\14\1\15\1\2"+
    "\1\16\1\17\1\20\1\21\1\22\2\21\1\23\2\21"+
    "\1\24\3\21\1\25\1\26\1\21\1\27\1\21\1\30"+
    "\3\21\1\31\1\32\1\7\7\21\1\33\2\21\1\34"+
    "\1\35\1\36\1\13\1\6\76\0\1\3\100\0\1\7"+
    "\3\0\1\7\1\0\3\7\5\0\25\7\2\0\13\7"+
    "\6\0\4\13\10\0\3\13\4\0\26\13\3\0\12\13"+
    "\3\0\1\13\25\0\1\37\50\0\4\13\2\0\1\7"+
    "\3\0\1\7\1\0\3\21\4\0\1\13\17\21\1\40"+
    "\5\21\2\0\1\7\12\21\3\0\1\13\2\0\4\13"+
    "\2\0\1\7\3\0\1\7\1\0\3\21\4\0\1\13"+
    "\25\21\2\0\1\7\12\21\3\0\1\13\2\0\4\13"+
    "\2\0\1\7\3\0\1\7\1\0\3\21\4\0\1\13"+
    "\1\41\6\21\1\42\5\21\1\43\1\21\1\44\5\21"+
    "\2\0\1\7\12\21\3\0\1\13\2\0\4\13\2\0"+
    "\1\7\3\0\1\7\1\0\3\21\4\0\1\13\4\21"+
    "\1\45\3\21\1\46\14\21\2\0\1\7\12\21\3\0"+
    "\1\13\2\0\4\13\2\0\1\7\3\0\1\7\1\0"+
    "\3\21\4\0\1\13\3\21\1\47\10\21\1\50\10\21"+
    "\2\0\1\7\12\21\3\0\1\13\2\0\4\13\2\0"+
    "\1\7\3\0\1\7\1\0\3\21\4\0\1\13\15\21"+
    "\1\51\7\21\2\0\1\7\12\21\3\0\1\13\2\0"+
    "\4\13\2\0\1\7\3\0\1\7\1\0\3\21\4\0"+
    "\1\13\16\21\1\52\6\21\2\0\1\7\12\21\3\0"+
    "\1\13\2\0\4\13\2\0\1\7\3\0\1\7\1\0"+
    "\3\21\4\0\1\13\1\53\3\21\1\54\20\21\2\0"+
    "\1\7\12\21\3\0\1\13\2\0\4\13\2\0\1\7"+
    "\3\0\1\7\1\0\3\21\4\0\1\13\4\21\1\55"+
    "\3\21\1\56\6\21\1\57\5\21\2\0\1\7\12\21"+
    "\3\0\1\13\2\0\4\13\2\0\1\7\3\0\1\7"+
    "\1\0\3\21\4\0\1\13\25\21\2\0\1\7\5\21"+
    "\1\60\4\21\3\0\1\13\67\0\1\61\6\0\4\13"+
    "\2\0\1\7\3\0\1\7\1\0\3\21\4\0\1\13"+
    "\4\21\1\62\20\21\2\0\1\7\12\21\3\0\1\13"+
    "\2\0\4\13\2\0\1\7\3\0\1\7\1\0\3\21"+
    "\4\0\1\13\13\21\1\63\11\21\2\0\1\7\12\21"+
    "\3\0\1\13\2\0\4\13\2\0\1\7\3\0\1\7"+
    "\1\0\3\21\4\0\1\13\4\21\1\64\20\21\2\0"+
    "\1\7\12\21\3\0\1\13\2\0\4\13\2\0\1\7"+
    "\3\0\1\7\1\0\3\21\4\0\1\13\12\21\1\65"+
    "\1\66\11\21\2\0\1\7\12\21\3\0\1\13\2\0"+
    "\4\13\2\0\1\7\3\0\1\7\1\0\3\21\4\0"+
    "\1\13\4\21\1\67\20\21\2\0\1\7\12\21\3\0"+
    "\1\13\2\0\4\13\2\0\1\7\3\0\1\7\1\0"+
    "\3\21\4\0\1\13\2\21\1\70\22\21\2\0\1\7"+
    "\12\21\3\0\1\13\2\0\4\13\2\0\1\7\3\0"+
    "\1\7\1\0\3\21\4\0\1\13\2\21\1\71\7\21"+
    "\1\72\12\21\2\0\1\7\12\21\3\0\1\13\2\0"+
    "\4\13\2\0\1\7\3\0\1\7\1\0\3\21\4\0"+
    "\1\13\25\21\2\0\1\73\12\21\3\0\1\13\2\0"+
    "\4\13\2\0\1\7\3\0\1\7\1\0\3\21\4\0"+
    "\1\13\3\21\1\74\21\21\2\0\1\7\12\21\3\0"+
    "\1\13\2\0\4\13\2\0\1\7\3\0\1\7\1\0"+
    "\3\21\4\0\1\13\13\21\1\75\11\21\2\0\1\7"+
    "\12\21\3\0\1\13\2\0\4\13\2\0\1\7\3\0"+
    "\1\7\1\0\3\21\4\0\1\13\2\21\1\76\22\21"+
    "\2\0\1\7\12\21\3\0\1\13\2\0\4\13\2\0"+
    "\1\7\3\0\1\7\1\0\3\21\4\0\1\13\3\21"+
    "\1\77\21\21\2\0\1\7\12\21\3\0\1\13\2\0"+
    "\4\13\2\0\1\7\3\0\1\7\1\0\3\21\4\0"+
    "\1\13\20\21\1\100\4\21\2\0\1\7\12\21\3\0"+
    "\1\13\2\0\4\13\2\0\1\7\3\0\1\7\1\0"+
    "\3\21\4\0\1\13\13\21\1\101\10\21\1\102\2\0"+
    "\1\7\12\21\3\0\1\13\2\0\4\13\2\0\1\7"+
    "\3\0\1\7\1\0\3\21\4\0\1\13\4\21\1\103"+
    "\20\21\2\0\1\7\12\21\3\0\1\13\2\0\4\13"+
    "\2\0\1\7\3\0\1\7\1\0\3\21\4\0\1\13"+
    "\10\21\1\104\14\21\2\0\1\7\12\21\3\0\1\13"+
    "\2\0\4\13\2\0\1\7\3\0\1\7\1\0\3\21"+
    "\4\0\1\13\25\21\2\0\1\7\2\21\1\105\7\21"+
    "\3\0\1\13\64\0\1\106\11\0\4\13\2\0\1\7"+
    "\3\0\1\7\1\0\3\21\4\0\1\13\1\107\24\21"+
    "\2\0\1\7\12\21\3\0\1\13\2\0\4\13\2\0"+
    "\1\7\3\0\1\7\1\0\3\21\4\0\1\13\16\21"+
    "\1\110\6\21\2\0\1\7\12\21\3\0\1\13\2\0"+
    "\4\13\2\0\1\7\3\0\1\7\1\0\3\21\4\0"+
    "\1\13\2\21\1\111\22\21\2\0\1\7\12\21\3\0"+
    "\1\13\2\0\4\13\2\0\1\7\3\0\1\7\1\0"+
    "\3\21\4\0\1\13\22\21\1\112\2\21\2\0\1\7"+
    "\12\21\3\0\1\13\2\0\4\13\2\0\1\7\3\0"+
    "\1\7\1\0\3\21\4\0\1\13\1\21\1\113\23\21"+
    "\2\0\1\7\12\21\3\0\1\13\2\0\4\13\2\0"+
    "\1\7\3\0\1\7\1\0\3\21\4\0\1\13\1\114"+
    "\24\21\2\0\1\7\12\21\3\0\1\13\2\0\4\13"+
    "\2\0\1\7\3\0\1\7\1\0\3\21\4\0\1\13"+
    "\7\21\1\115\15\21\2\0\1\7\12\21\3\0\1\13"+
    "\2\0\4\13\2\0\1\7\3\0\1\7\1\0\3\21"+
    "\4\0\1\13\7\21\1\116\15\21\2\0\1\7\12\21"+
    "\3\0\1\13\2\0\4\13\2\0\1\7\3\0\1\7"+
    "\1\0\3\21\4\0\1\13\1\117\24\21\2\0\1\7"+
    "\12\21\3\0\1\13\10\0\1\7\3\0\1\7\1\0"+
    "\3\7\5\0\21\7\1\120\3\7\2\0\13\7\6\0"+
    "\4\13\2\0\1\7\3\0\1\7\1\0\3\21\4\0"+
    "\1\13\10\21\1\121\14\21\2\0\1\7\12\21\3\0"+
    "\1\13\2\0\4\13\2\0\1\7\3\0\1\7\1\0"+
    "\3\21\4\0\1\13\1\21\1\122\23\21\2\0\1\7"+
    "\12\21\3\0\1\13\2\0\4\13\2\0\1\7\3\0"+
    "\1\7\1\0\3\21\4\0\1\13\10\21\1\123\14\21"+
    "\2\0\1\7\12\21\3\0\1\13\2\0\4\13\2\0"+
    "\1\7\3\0\1\7\1\0\3\21\4\0\1\13\10\21"+
    "\1\124\14\21\2\0\1\7\12\21\3\0\1\13\2\0"+
    "\4\13\2\0\1\7\3\0\1\7\1\0\3\21\4\0"+
    "\1\13\16\21\1\125\6\21\2\0\1\7\12\21\3\0"+
    "\1\13\2\0\4\13\2\0\1\7\3\0\1\7\1\0"+
    "\3\21\4\0\1\13\1\126\24\21\2\0\1\7\12\21"+
    "\3\0\1\13\2\0\4\13\2\0\1\7\3\0\1\7"+
    "\1\0\3\21\4\0\1\13\21\21\1\127\3\21\2\0"+
    "\1\7\12\21\3\0\1\13\2\0\4\13\2\0\1\7"+
    "\3\0\1\7\1\0\3\21\4\0\1\13\13\21\1\130"+
    "\11\21\2\0\1\7\12\21\3\0\1\13\2\0\4\13"+
    "\2\0\1\7\3\0\1\7\1\0\3\21\4\0\1\13"+
    "\23\21\1\131\1\21\2\0\1\7\12\21\3\0\1\13"+
    "\2\0\4\13\2\0\1\7\3\0\1\7\1\0\3\21"+
    "\4\0\1\13\25\21\2\0\1\7\10\21\1\132\1\21"+
    "\3\0\1\13\62\0\1\133\13\0\4\13\2\0\1\7"+
    "\3\0\1\7\1\0\3\21\4\0\1\13\25\21\2\0"+
    "\1\134\12\21\3\0\1\13\2\0\4\13\2\0\1\7"+
    "\3\0\1\7\1\0\3\21\4\0\1\13\15\21\1\135"+
    "\7\21\2\0\1\7\12\21\3\0\1\13\2\0\4\13"+
    "\2\0\1\7\3\0\1\7\1\0\3\21\4\0\1\13"+
    "\11\21\1\136\13\21\2\0\1\7\12\21\3\0\1\13"+
    "\2\0\4\13\2\0\1\7\3\0\1\7\1\0\3\21"+
    "\4\0\1\13\13\21\1\137\11\21\2\0\1\7\12\21"+
    "\3\0\1\13\2\0\4\13\2\0\1\7\3\0\1\7"+
    "\1\0\3\21\4\0\1\13\15\21\1\140\7\21\2\0"+
    "\1\7\12\21\3\0\1\13\2\0\4\13\2\0\1\7"+
    "\3\0\1\7\1\0\3\21\4\0\1\13\3\21\1\141"+
    "\21\21\2\0\1\7\12\21\3\0\1\13\2\0\4\13"+
    "\2\0\1\7\3\0\1\7\1\0\3\21\4\0\1\13"+
    "\1\142\24\21\2\0\1\7\12\21\3\0\1\13\2\0"+
    "\4\13\2\0\1\7\3\0\1\7\1\0\3\21\4\0"+
    "\1\13\4\21\1\143\20\21\2\0\1\7\12\21\3\0"+
    "\1\13\2\0\4\13\2\0\1\7\3\0\1\7\1\0"+
    "\3\21\4\0\1\13\20\21\1\144\4\21\2\0\1\7"+
    "\12\21\3\0\1\13\10\0\1\7\3\0\1\7\1\0"+
    "\3\7\5\0\17\7\1\145\5\7\2\0\13\7\6\0"+
    "\4\13\2\0\1\7\3\0\1\7\1\0\3\21\4\0"+
    "\1\13\2\21\1\146\22\21\2\0\1\7\12\21\3\0"+
    "\1\13\2\0\4\13\2\0\1\7\3\0\1\7\1\0"+
    "\3\21\4\0\1\13\17\21\1\147\5\21\2\0\1\7"+
    "\12\21\3\0\1\13\2\0\4\13\2\0\1\7\3\0"+
    "\1\7\1\0\3\21\4\0\1\13\15\21\1\150\7\21"+
    "\2\0\1\7\12\21\3\0\1\13\2\0\4\13\2\0"+
    "\1\7\3\0\1\7\1\0\3\21\4\0\1\13\15\21"+
    "\1\151\7\21\2\0\1\7\12\21\3\0\1\13\2\0"+
    "\4\13\2\0\1\7\3\0\1\7\1\0\3\21\4\0"+
    "\1\13\22\21\1\152\2\21\2\0\1\7\12\21\3\0"+
    "\1\13\2\0\4\13\2\0\1\7\3\0\1\7\1\0"+
    "\3\21\4\0\1\13\15\21\1\153\7\21\2\0\1\7"+
    "\12\21\3\0\1\13\2\0\4\13\2\0\1\7\3\0"+
    "\1\7\1\0\3\21\4\0\1\13\16\21\1\154\6\21"+
    "\2\0\1\7\12\21\3\0\1\13\2\0\4\13\2\0"+
    "\1\7\3\0\1\7\1\0\3\21\4\0\1\13\10\21"+
    "\1\155\14\21\2\0\1\7\12\21\3\0\1\13\2\0"+
    "\4\13\2\0\1\7\3\0\1\7\1\0\3\21\4\0"+
    "\1\13\25\21\2\0\1\7\2\21\1\156\7\21\3\0"+
    "\1\13\61\0\1\157\22\0\1\7\3\0\1\7\1\0"+
    "\3\7\5\0\21\7\1\160\3\7\2\0\13\7\6\0"+
    "\4\13\2\0\1\7\3\0\1\7\1\0\3\21\4\0"+
    "\1\13\25\21\2\0\1\161\12\21\3\0\1\13\2\0"+
    "\4\13\2\0\1\7\3\0\1\162\1\0\3\21\4\0"+
    "\1\13\25\21\2\0\1\7\12\21\3\0\1\13\2\0"+
    "\4\13\2\0\1\7\3\0\1\7\1\0\3\21\4\0"+
    "\1\13\14\21\1\163\10\21\2\0\1\7\12\21\3\0"+
    "\1\13\2\0\4\13\2\0\1\7\3\0\1\7\1\0"+
    "\3\21\4\0\1\13\15\21\1\164\7\21\2\0\1\7"+
    "\12\21\3\0\1\13\2\0\4\13\2\0\1\7\3\0"+
    "\1\7\1\0\3\21\4\0\1\13\17\21\1\165\5\21"+
    "\2\0\1\7\12\21\3\0\1\13\10\0\1\7\3\0"+
    "\1\7\1\0\3\7\5\0\10\7\1\166\14\7\2\0"+
    "\13\7\6\0\4\13\2\0\1\7\3\0\1\7\1\0"+
    "\3\21\4\0\1\13\4\21\1\167\20\21\2\0\1\7"+
    "\12\21\3\0\1\13\2\0\4\13\2\0\1\7\3\0"+
    "\1\7\1\0\3\21\4\0\1\13\4\21\1\170\20\21"+
    "\2\0\1\7\12\21\3\0\1\13\2\0\4\13\2\0"+
    "\1\7\3\0\1\7\1\0\3\21\4\0\1\13\14\21"+
    "\1\171\10\21\2\0\1\7\12\21\3\0\1\13\2\0"+
    "\4\13\2\0\1\7\3\0\1\7\1\0\3\21\4\0"+
    "\1\13\4\21\1\172\20\21\2\0\1\7\12\21\3\0"+
    "\1\13\2\0\4\13\2\0\1\7\3\0\1\7\1\0"+
    "\3\21\4\0\1\13\25\21\2\0\1\173\12\21\3\0"+
    "\1\13\2\0\4\13\2\0\1\7\3\0\1\7\1\0"+
    "\3\21\4\0\1\13\15\21\1\174\7\21\2\0\1\7"+
    "\12\21\3\0\1\13\2\0\4\13\2\0\1\7\3\0"+
    "\1\7\1\0\3\21\4\0\1\13\1\175\24\21\2\0"+
    "\1\7\12\21\3\0\1\13\2\0\4\13\2\0\1\7"+
    "\3\0\1\7\1\0\3\21\4\0\1\13\25\21\2\0"+
    "\1\7\1\176\11\21\3\0\1\13\5\0\1\177\76\0"+
    "\1\7\3\0\1\7\1\0\3\7\5\0\4\7\1\200"+
    "\20\7\2\0\13\7\14\0\1\7\3\0\1\7\1\0"+
    "\3\7\5\0\21\7\1\201\3\7\2\0\13\7\14\0"+
    "\1\7\3\0\1\7\1\0\3\7\5\0\1\7\1\202"+
    "\23\7\2\0\13\7\6\0\4\13\2\0\1\7\3\0"+
    "\1\7\1\0\3\21\4\0\1\13\1\203\24\21\2\0"+
    "\1\7\12\21\3\0\1\13\2\0\4\13\2\0\1\7"+
    "\3\0\1\7\1\0\3\21\4\0\1\13\17\21\1\204"+
    "\5\21\2\0\1\7\12\21\3\0\1\13\2\0\4\13"+
    "\2\0\1\7\3\0\1\7\1\0\3\21\4\0\1\13"+
    "\15\21\1\205\7\21\2\0\1\7\12\21\3\0\1\13"+
    "\10\0\1\7\3\0\1\7\1\0\3\7\5\0\23\7"+
    "\1\206\1\7\2\0\13\7\6\0\4\13\2\0\1\7"+
    "\3\0\1\7\1\0\3\21\4\0\1\13\4\21\1\207"+
    "\20\21\2\0\1\7\12\21\3\0\1\13\2\0\4\13"+
    "\2\0\1\7\3\0\1\7\1\0\3\21\4\0\1\13"+
    "\20\21\1\210\4\21\2\0\1\7\12\21\3\0\1\13"+
    "\10\0\1\7\3\0\1\7\1\0\3\7\5\0\23\7"+
    "\1\211\1\7\2\0\13\7\72\0\1\212\15\0\1\7"+
    "\3\0\1\7\1\0\3\7\5\0\24\7\1\213\2\0"+
    "\13\7\14\0\1\7\3\0\1\7\1\0\3\7\5\0"+
    "\4\7\1\214\20\7\2\0\13\7\14\0\1\7\3\0"+
    "\1\7\1\0\3\7\5\0\15\7\1\215\7\7\2\0"+
    "\13\7\6\0\4\13\2\0\1\7\3\0\1\7\1\0"+
    "\3\21\4\0\1\13\20\21\1\216\4\21\2\0\1\7"+
    "\12\21\3\0\1\13\10\0\1\7\3\0\1\7\1\0"+
    "\3\7\5\0\10\7\1\217\14\7\2\0\13\7\6\0"+
    "\4\13\2\0\1\7\3\0\1\7\1\0\3\21\4\0"+
    "\1\13\20\21\1\220\4\21\2\0\1\7\12\21\3\0"+
    "\1\13\2\0\4\13\2\0\1\7\3\0\1\7\1\0"+
    "\3\21\4\0\1\13\21\21\1\221\3\21\2\0\1\7"+
    "\12\21\3\0\1\13\10\0\1\7\3\0\1\7\1\0"+
    "\3\7\5\0\10\7\1\222\14\7\2\0\13\7\63\0"+
    "\1\223\24\0\1\7\3\0\1\7\1\0\3\7\5\0"+
    "\21\7\1\224\3\7\2\0\13\7\14\0\1\7\3\0"+
    "\1\7\1\0\3\7\5\0\24\7\1\225\2\0\13\7"+
    "\14\0\1\7\3\0\1\7\1\0\3\7\5\0\24\7"+
    "\1\226\2\0\13\7\14\0\1\7\3\0\1\7\1\0"+
    "\3\7\5\0\1\227\24\7\2\0\13\7\6\0\4\13"+
    "\2\0\1\7\3\0\1\7\1\0\3\21\4\0\1\13"+
    "\1\230\24\21\2\0\1\7\12\21\3\0\1\13\10\0"+
    "\1\7\3\0\1\7\1\0\3\7\5\0\20\7\1\231"+
    "\4\7\2\0\13\7\67\0\1\232\20\0\1\7\3\0"+
    "\1\7\1\0\3\7\5\0\15\7\1\233\7\7\2\0"+
    "\13\7\14\0\1\7\3\0\1\7\1\0\3\7\5\0"+
    "\21\7\1\234\3\7\2\0\13\7\14\0\1\7\3\0"+
    "\1\7\1\0\3\7\5\0\10\7\1\235\14\7\2\0"+
    "\13\7\70\0\1\236\17\0\1\7\3\0\1\7\1\0"+
    "\3\7\5\0\15\7\1\237\7\7\2\0\13\7\14\0"+
    "\1\7\3\0\1\7\1\0\3\7\5\0\1\7\1\240"+
    "\23\7\2\0\13\7\64\0\1\241\23\0\1\7\3\0"+
    "\1\7\1\0\3\7\5\0\12\7\1\242\12\7\2\0"+
    "\13\7\66\0\1\243\21\0\1\7\3\0\1\7\1\0"+
    "\3\7\5\0\4\7\1\244\20\7\2\0\13\7\65\0"+
    "\1\245\35\0\1\246\57\0\1\247\103\0\1\250\71\0"+
    "\1\251\74\0\1\252\64\0\1\253\71\0\1\254\113\0"+
    "\1\255\72\0\1\256\50\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[8340];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\1\1\2\11\1\1\3\11\1\1\1\11"+
    "\1\1\2\11\11\1\2\11\1\1\3\11\1\0\21\1"+
    "\1\0\24\1\1\0\24\1\1\0\23\1\1\0\17\1"+
    "\1\0\12\1\1\0\10\1\1\0\6\1\1\0\3\1"+
    "\1\0\2\1\1\0\1\1\1\0\1\1\11\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[174];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    private Symbol symbol(int type){
        return new Symbol(type, yyline +1, yycolumn +1);
    }

    private Symbol symbol(int type, Object value){
        System.out.println("Token con valor reconocido: " + yytext());
        return new Symbol(type, yyline +1, yycolumn + 1, value);
    }

    private void error (String message){
        System.out.println("Error en la linea: " + (yyline +1) + " columna: " + (yycolumn +1) + " : " + message);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
              {
                return symbol(sym.EOF);
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { System.out.println("No se reconocio el lexema " + yytext() + " como un token valido y se ignoro.");
                 //errores.agregarError(yytext(), yyline +1, yycolumn + 1, "Lexico", "El simbolo no se encuentra definido en el alfabeto.");
            }
          // fall through
          case 40: break;
          case 2:
            { /* Ignorar */
            }
          // fall through
          case 41: break;
          case 3:
            { return symbol(sym.EXCLAM);
            }
          // fall through
          case 42: break;
          case 4:
            { return symbol(sym.COMILL);
            }
          // fall through
          case 43: break;
          case 5:
            { return symbol(sym.IDENTIFICADOR, yytext());
            }
          // fall through
          case 44: break;
          case 6:
            { return symbol(sym.PAROPN);
            }
          // fall through
          case 45: break;
          case 7:
            { return symbol(sym.PARCLS);
            }
          // fall through
          case 46: break;
          case 8:
            { return symbol(sym.COMMA);
            }
          // fall through
          case 47: break;
          case 9:
            { return symbol(sym.STRING, yytext());
            }
          // fall through
          case 48: break;
          case 10:
            { return symbol(sym.DOSPUN);
            }
          // fall through
          case 49: break;
          case 11:
            { return symbol(sym.MENQUE);
            }
          // fall through
          case 50: break;
          case 12:
            { return symbol(sym.MAYQUE);
            }
          // fall through
          case 51: break;
          case 13:
            { return symbol(sym.QSTMRK);
            }
          // fall through
          case 52: break;
          case 14:
            { return symbol(sym.COROPN);
            }
          // fall through
          case 53: break;
          case 15:
            { return symbol(sym.CORCLS);
            }
          // fall through
          case 54: break;
          case 16:
            { return symbol(sym.LLAVOP);
            }
          // fall through
          case 55: break;
          case 17:
            { return symbol(sym.ORSYMB);
            }
          // fall through
          case 56: break;
          case 18:
            { return symbol(sym.LLAVCL);
            }
          // fall through
          case 57: break;
          case 19:
            { return symbol(sym.TEMA  );
            }
          // fall through
          case 58: break;
          case 20:
            { return symbol(sym.COMBO  );
            }
          // fall through
          case 59: break;
          case 21:
            { return symbol(sym.FECHA );
            }
          // fall through
          case 60: break;
          case 22:
            { return symbol(sym.PARAM_FIL);
            }
          // fall through
          case 61: break;
          case 23:
            { return symbol(sym.RADIO  );
            }
          // fall through
          case 62: break;
          case 24:
            { return symbol(sym.PARAM_IND);
            }
          // fall through
          case 63: break;
          case 25:
            { return symbol(sym.NOMBRE);
            }
          // fall through
          case 64: break;
          case 26:
            { return symbol(sym.TIEMPO);
            }
          // fall through
          case 65: break;
          case 27:
            { return symbol(sym.PARAM_TRI);
            }
          // fall through
          case 66: break;
          case 28:
            { return symbol(sym.TRIVIA);
            }
          // fall through
          case 67: break;
          case 29:
            { return symbol(sym.CREADO);
            }
          // fall through
          case 68: break;
          case 30:
            { return symbol(sym.FICHERO);
            }
          // fall through
          case 69: break;
          case 31:
            { return symbol(sym.PARAM_COL);
            }
          // fall through
          case 70: break;
          case 32:
            { return symbol(sym.PARAM_OPC);
            }
          // fall through
          case 71: break;
          case 33:
            { // Acción a realizar cuando se encuentra "CHECK-BOX"
        return symbol(sym.CHECKBO);
            }
          // fall through
          case 72: break;
          case 34:
            { return symbol(sym.ID_TRI);
            }
          // fall through
          case 73: break;
          case 35:
            { return symbol(sym.PARAM_RES);
            }
          // fall through
          case 74: break;
          case 36:
            { return symbol(sym.AREA_TE);
            }
          // fall through
          case 75: break;
          case 37:
            { return symbol(sym.CAMPO_T);
            }
          // fall through
          case 76: break;
          case 38:
            { return symbol(sym.PARAM_TEX);
            }
          // fall through
          case 77: break;
          case 39:
            { return symbol(sym.ENCABEZADO);
            }
          // fall through
          case 78: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
