
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.jbrod.servidorprincipal.analizadores.consultas;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 17;
  public static final int SELEC_REPORTE = 19;
  public static final int OR = 18;
  public static final int DOSPUN = 7;
  public static final int COMILL = 14;
  public static final int QSTMRK = 13;
  public static final int FILTRAR = 20;
  public static final int LLAVCL = 9;
  public static final int LLAVOP = 8;
  public static final int EQUALS = 16;
  public static final int COMMA = 12;
  public static final int ORSYMB = 15;
  public static final int EOF = 0;
  public static final int EXCLAM = 6;
  public static final int TIEMPO = 21;
  public static final int CORCLS = 11;
  public static final int USUARIO = 22;
  public static final int error = 1;
  public static final int NUMERO = 2;
  public static final int MENQUE = 4;
  public static final int IDENTIFICADOR = 3;
  public static final int COROPN = 10;
  public static final int MAYQUE = 5;
  public static final int PUNTUAC = 23;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NUMERO",
  "IDENTIFICADOR",
  "MENQUE",
  "MAYQUE",
  "EXCLAM",
  "DOSPUN",
  "LLAVOP",
  "LLAVCL",
  "COROPN",
  "CORCLS",
  "COMMA",
  "QSTMRK",
  "COMILL",
  "ORSYMB",
  "EQUALS",
  "AND",
  "OR",
  "SELEC_REPORTE",
  "FILTRAR",
  "TIEMPO",
  "USUARIO",
  "PUNTUAC"
  };
}

