// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: LexerTrivias.flex

/* - - - - - - - - - - - - - - - - - CODIGO DE USUARIO - - - - - - - - - - - - - - - - - */
package com.jbrod.servidorprincipal.analizadores.carga.trivias;

import java_cup.runtime.*;


@SuppressWarnings("fallthrough")
public class LexerTrivias implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\25\u0100\1\u0200\11\u0100\1\u0300\17\u0100\1\u0400\u10cf\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\1\1\3\22\0\1\1\1\4"+
    "\1\5\1\0\1\6\3\0\1\7\1\10\2\0\1\11"+
    "\1\12\2\0\12\13\1\14\1\0\1\15\1\0\1\16"+
    "\1\17\1\0\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\30\1\26\1\31\1\32\1\33\1\34"+
    "\1\35\1\36\1\26\1\37\1\40\1\41\1\42\1\43"+
    "\1\26\1\44\2\26\1\45\1\0\1\46\1\0\1\47"+
    "\1\0\1\50\7\26\1\51\10\26\1\52\1\26\1\53"+
    "\1\26\1\54\4\26\1\55\1\56\1\57\7\0\1\1"+
    "\32\0\1\1\36\0\1\60\u01c0\0\1\1\177\0\13\1"+
    "\21\0\2\5\12\0\2\1\5\0\1\1\57\0\1\1"+
    "\240\0\1\1\377\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1280];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\11\5\1\16"+
    "\1\17\1\5\1\20\1\21\1\22\1\0\21\5\1\0"+
    "\24\5\1\0\17\5\1\23\4\5\1\0\4\5\1\24"+
    "\1\5\1\25\1\5\1\26\4\5\1\27\5\5\1\0"+
    "\7\5\1\30\1\31\3\5\1\32\1\33\1\34\1\0"+
    "\4\5\1\35\1\36\4\5\1\37\1\0\3\5\1\40"+
    "\1\5\1\41\2\5\1\0\2\5\1\42\1\43\1\44"+
    "\1\5\1\0\1\45\2\5\1\0\1\46\1\5\1\0"+
    "\1\5\1\0\1\47\1\0\1\50";

  private static int [] zzUnpackAction() {
    int [] result = new int[167];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\61\0\61\0\142\0\61\0\61\0\223\0\61"+
    "\0\61\0\61\0\304\0\61\0\365\0\61\0\61\0\u0126"+
    "\0\u0157\0\u0188\0\u01b9\0\u01ea\0\u021b\0\u024c\0\u027d\0\u02ae"+
    "\0\61\0\61\0\u02df\0\61\0\61\0\61\0\u0310\0\u0341"+
    "\0\u0372\0\u03a3\0\u03d4\0\u0405\0\u0436\0\u0467\0\u0498\0\u04c9"+
    "\0\u04fa\0\u052b\0\u055c\0\u058d\0\u05be\0\u05ef\0\u0620\0\u0651"+
    "\0\u0682\0\u06b3\0\u06e4\0\u0715\0\u0746\0\u0777\0\u07a8\0\u07d9"+
    "\0\u080a\0\u083b\0\u086c\0\u089d\0\u08ce\0\u08ff\0\u0930\0\u0961"+
    "\0\u0992\0\u09c3\0\u09f4\0\u0a25\0\u0a56\0\u0a87\0\u0ab8\0\u0ae9"+
    "\0\u0b1a\0\u0b4b\0\u0b7c\0\u0bad\0\u0bde\0\u0c0f\0\u0c40\0\u0c71"+
    "\0\u0ca2\0\u0cd3\0\u0d04\0\u0d35\0\u0d66\0\u0157\0\u0d97\0\u0dc8"+
    "\0\u0df9\0\u0e2a\0\u0e5b\0\u0e8c\0\u0ebd\0\u0eee\0\u0f1f\0\u0157"+
    "\0\u0f50\0\u0157\0\u0f81\0\u0157\0\u0fb2\0\u0fe3\0\u1014\0\u1045"+
    "\0\u0157\0\u1076\0\u10a7\0\u10d8\0\u1109\0\u113a\0\u116b\0\u119c"+
    "\0\u11cd\0\u11fe\0\u122f\0\u1260\0\u1291\0\u12c2\0\u0157\0\u0157"+
    "\0\u12f3\0\u1324\0\u1355\0\u0157\0\u1386\0\u0157\0\u13b7\0\u13e8"+
    "\0\u1419\0\u144a\0\u147b\0\u0157\0\u0157\0\u14ac\0\u14dd\0\u150e"+
    "\0\u153f\0\u0157\0\u1570\0\u15a1\0\u15d2\0\u1603\0\u0157\0\u1634"+
    "\0\u0157\0\u1665\0\u1696\0\u16c7\0\u16f8\0\u1729\0\223\0\223"+
    "\0\u0157\0\u175a\0\u178b\0\223\0\u17bc\0\u17ed\0\u181e\0\223"+
    "\0\u184f\0\u1880\0\u18b1\0\u18e2\0\223\0\u1913\0\61";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[167];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\7\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\2\21\1\23\2\21\1\24\3\21\1\25"+
    "\1\26\1\21\1\27\1\21\1\30\3\21\1\31\1\32"+
    "\1\7\3\21\1\33\1\21\1\34\1\35\1\36\1\13"+
    "\63\0\1\3\64\0\1\7\3\0\2\7\4\0\25\7"+
    "\2\0\6\7\5\0\3\13\7\0\1\13\3\0\26\13"+
    "\3\0\5\13\3\0\1\13\21\0\1\37\40\0\3\13"+
    "\2\0\1\7\3\0\1\7\1\21\3\0\1\13\17\21"+
    "\1\40\5\21\2\0\1\7\5\21\3\0\1\13\1\0"+
    "\3\13\2\0\1\7\3\0\1\7\1\21\3\0\1\13"+
    "\25\21\2\0\1\7\5\21\3\0\1\13\1\0\3\13"+
    "\2\0\1\7\3\0\1\7\1\21\3\0\1\13\1\41"+
    "\6\21\1\42\5\21\1\43\1\21\1\44\5\21\2\0"+
    "\1\7\5\21\3\0\1\13\1\0\3\13\2\0\1\7"+
    "\3\0\1\7\1\21\3\0\1\13\4\21\1\45\3\21"+
    "\1\46\14\21\2\0\1\7\5\21\3\0\1\13\1\0"+
    "\3\13\2\0\1\7\3\0\1\7\1\21\3\0\1\13"+
    "\3\21\1\47\10\21\1\50\10\21\2\0\1\7\5\21"+
    "\3\0\1\13\1\0\3\13\2\0\1\7\3\0\1\7"+
    "\1\21\3\0\1\13\15\21\1\51\7\21\2\0\1\7"+
    "\5\21\3\0\1\13\1\0\3\13\2\0\1\7\3\0"+
    "\1\7\1\21\3\0\1\13\16\21\1\52\6\21\2\0"+
    "\1\7\5\21\3\0\1\13\1\0\3\13\2\0\1\7"+
    "\3\0\1\7\1\21\3\0\1\13\1\53\3\21\1\54"+
    "\20\21\2\0\1\7\5\21\3\0\1\13\1\0\3\13"+
    "\2\0\1\7\3\0\1\7\1\21\3\0\1\13\4\21"+
    "\1\55\3\21\1\56\6\21\1\57\5\21\2\0\1\7"+
    "\5\21\3\0\1\13\1\0\3\13\2\0\1\7\3\0"+
    "\1\7\1\21\3\0\1\13\25\21\2\0\1\7\2\21"+
    "\1\60\2\21\3\0\1\13\20\0\1\61\41\0\3\13"+
    "\2\0\1\7\3\0\1\7\1\21\3\0\1\13\4\21"+
    "\1\62\20\21\2\0\1\7\5\21\3\0\1\13\1\0"+
    "\3\13\2\0\1\7\3\0\1\7\1\21\3\0\1\13"+
    "\13\21\1\63\11\21\2\0\1\7\5\21\3\0\1\13"+
    "\1\0\3\13\2\0\1\7\3\0\1\7\1\21\3\0"+
    "\1\13\4\21\1\64\20\21\2\0\1\7\5\21\3\0"+
    "\1\13\1\0\3\13\2\0\1\7\3\0\1\7\1\21"+
    "\3\0\1\13\12\21\1\65\1\66\11\21\2\0\1\7"+
    "\5\21\3\0\1\13\1\0\3\13\2\0\1\7\3\0"+
    "\1\7\1\21\3\0\1\13\4\21\1\67\20\21\2\0"+
    "\1\7\5\21\3\0\1\13\1\0\3\13\2\0\1\7"+
    "\3\0\1\7\1\21\3\0\1\13\2\21\1\70\22\21"+
    "\2\0\1\7\5\21\3\0\1\13\1\0\3\13\2\0"+
    "\1\7\3\0\1\7\1\21\3\0\1\13\2\21\1\71"+
    "\7\21\1\72\12\21\2\0\1\7\5\21\3\0\1\13"+
    "\1\0\3\13\2\0\1\7\3\0\1\7\1\21\3\0"+
    "\1\13\25\21\2\0\1\73\5\21\3\0\1\13\1\0"+
    "\3\13\2\0\1\7\3\0\1\7\1\21\3\0\1\13"+
    "\3\21\1\74\21\21\2\0\1\7\5\21\3\0\1\13"+
    "\1\0\3\13\2\0\1\7\3\0\1\7\1\21\3\0"+
    "\1\13\13\21\1\75\11\21\2\0\1\7\5\21\3\0"+
    "\1\13\1\0\3\13\2\0\1\7\3\0\1\7\1\21"+
    "\3\0\1\13\2\21\1\76\22\21\2\0\1\7\5\21"+
    "\3\0\1\13\1\0\3\13\2\0\1\7\3\0\1\7"+
    "\1\21\3\0\1\13\3\21\1\77\21\21\2\0\1\7"+
    "\5\21\3\0\1\13\1\0\3\13\2\0\1\7\3\0"+
    "\1\7\1\21\3\0\1\13\20\21\1\100\4\21\2\0"+
    "\1\7\5\21\3\0\1\13\1\0\3\13\2\0\1\7"+
    "\3\0\1\7\1\21\3\0\1\13\13\21\1\101\10\21"+
    "\1\102\2\0\1\7\5\21\3\0\1\13\1\0\3\13"+
    "\2\0\1\7\3\0\1\7\1\21\3\0\1\13\4\21"+
    "\1\103\20\21\2\0\1\7\5\21\3\0\1\13\1\0"+
    "\3\13\2\0\1\7\3\0\1\7\1\21\3\0\1\13"+
    "\10\21\1\104\14\21\2\0\1\7\5\21\3\0\1\13"+
    "\1\0\3\13\2\0\1\7\3\0\1\7\1\21\3\0"+
    "\1\13\25\21\2\0\1\7\1\21\1\105\3\21\3\0"+
    "\1\13\40\0\1\106\21\0\3\13\2\0\1\7\3\0"+
    "\1\7\1\21\3\0\1\13\1\107\24\21\2\0\1\7"+
    "\5\21\3\0\1\13\1\0\3\13\2\0\1\7\3\0"+
    "\1\7\1\21\3\0\1\13\16\21\1\110\6\21\2\0"+
    "\1\7\5\21\3\0\1\13\1\0\3\13\2\0\1\7"+
    "\3\0\1\7\1\21\3\0\1\13\2\21\1\111\22\21"+
    "\2\0\1\7\5\21\3\0\1\13\1\0\3\13\2\0"+
    "\1\7\3\0\1\7\1\21\3\0\1\13\22\21\1\112"+
    "\2\21\2\0\1\7\5\21\3\0\1\13\1\0\3\13"+
    "\2\0\1\7\3\0\1\7\1\21\3\0\1\13\1\21"+
    "\1\113\23\21\2\0\1\7\5\21\3\0\1\13\1\0"+
    "\3\13\2\0\1\7\3\0\1\7\1\21\3\0\1\13"+
    "\1\114\24\21\2\0\1\7\5\21\3\0\1\13\1\0"+
    "\3\13\2\0\1\7\3\0\1\7\1\21\3\0\1\13"+
    "\7\21\1\115\15\21\2\0\1\7\5\21\3\0\1\13"+
    "\1\0\3\13\2\0\1\7\3\0\1\7\1\21\3\0"+
    "\1\13\7\21\1\116\15\21\2\0\1\7\5\21\3\0"+
    "\1\13\1\0\3\13\2\0\1\7\3\0\1\7\1\21"+
    "\3\0\1\13\1\117\24\21\2\0\1\7\5\21\3\0"+
    "\1\13\6\0\1\7\3\0\2\7\4\0\21\7\1\120"+
    "\3\7\2\0\6\7\5\0\3\13\2\0\1\7\3\0"+
    "\1\7\1\21\3\0\1\13\10\21\1\121\14\21\2\0"+
    "\1\7\5\21\3\0\1\13\1\0\3\13\2\0\1\7"+
    "\3\0\1\7\1\21\3\0\1\13\1\21\1\122\23\21"+
    "\2\0\1\7\5\21\3\0\1\13\1\0\3\13\2\0"+
    "\1\7\3\0\1\7\1\21\3\0\1\13\10\21\1\123"+
    "\14\21\2\0\1\7\5\21\3\0\1\13\1\0\3\13"+
    "\2\0\1\7\3\0\1\7\1\21\3\0\1\13\10\21"+
    "\1\124\14\21\2\0\1\7\5\21\3\0\1\13\1\0"+
    "\3\13\2\0\1\7\3\0\1\7\1\21\3\0\1\13"+
    "\16\21\1\125\6\21\2\0\1\7\5\21\3\0\1\13"+
    "\1\0\3\13\2\0\1\7\3\0\1\7\1\21\3\0"+
    "\1\13\1\126\24\21\2\0\1\7\5\21\3\0\1\13"+
    "\1\0\3\13\2\0\1\7\3\0\1\7\1\21\3\0"+
    "\1\13\21\21\1\127\3\21\2\0\1\7\5\21\3\0"+
    "\1\13\1\0\3\13\2\0\1\7\3\0\1\7\1\21"+
    "\3\0\1\13\13\21\1\130\11\21\2\0\1\7\5\21"+
    "\3\0\1\13\1\0\3\13\2\0\1\7\3\0\1\7"+
    "\1\21\3\0\1\13\23\21\1\131\1\21\2\0\1\7"+
    "\5\21\3\0\1\13\1\0\3\13\2\0\1\7\3\0"+
    "\1\7\1\21\3\0\1\13\25\21\2\0\1\7\4\21"+
    "\1\132\3\0\1\13\24\0\1\133\35\0\3\13\2\0"+
    "\1\7\3\0\1\7\1\21\3\0\1\13\25\21\2\0"+
    "\1\134\5\21\3\0\1\13\1\0\3\13\2\0\1\7"+
    "\3\0\1\7\1\21\3\0\1\13\15\21\1\135\7\21"+
    "\2\0\1\7\5\21\3\0\1\13\1\0\3\13\2\0"+
    "\1\7\3\0\1\7\1\21\3\0\1\13\11\21\1\136"+
    "\13\21\2\0\1\7\5\21\3\0\1\13\1\0\3\13"+
    "\2\0\1\7\3\0\1\7\1\21\3\0\1\13\13\21"+
    "\1\137\11\21\2\0\1\7\5\21\3\0\1\13\1\0"+
    "\3\13\2\0\1\7\3\0\1\7\1\21\3\0\1\13"+
    "\15\21\1\140\7\21\2\0\1\7\5\21\3\0\1\13"+
    "\1\0\3\13\2\0\1\7\3\0\1\7\1\21\3\0"+
    "\1\13\3\21\1\141\21\21\2\0\1\7\5\21\3\0"+
    "\1\13\1\0\3\13\2\0\1\7\3\0\1\7\1\21"+
    "\3\0\1\13\1\142\24\21\2\0\1\7\5\21\3\0"+
    "\1\13\1\0\3\13\2\0\1\7\3\0\1\7\1\21"+
    "\3\0\1\13\4\21\1\143\20\21\2\0\1\7\5\21"+
    "\3\0\1\13\1\0\3\13\2\0\1\7\3\0\1\7"+
    "\1\21\3\0\1\13\20\21\1\144\4\21\2\0\1\7"+
    "\5\21\3\0\1\13\6\0\1\7\3\0\2\7\4\0"+
    "\17\7\1\145\5\7\2\0\6\7\5\0\3\13\2\0"+
    "\1\7\3\0\1\7\1\21\3\0\1\13\2\21\1\146"+
    "\22\21\2\0\1\7\5\21\3\0\1\13\1\0\3\13"+
    "\2\0\1\7\3\0\1\7\1\21\3\0\1\13\17\21"+
    "\1\147\5\21\2\0\1\7\5\21\3\0\1\13\1\0"+
    "\3\13\2\0\1\7\3\0\1\7\1\21\3\0\1\13"+
    "\15\21\1\150\7\21\2\0\1\7\5\21\3\0\1\13"+
    "\1\0\3\13\2\0\1\7\3\0\1\7\1\21\3\0"+
    "\1\13\15\21\1\151\7\21\2\0\1\7\5\21\3\0"+
    "\1\13\1\0\3\13\2\0\1\7\3\0\1\7\1\21"+
    "\3\0\1\13\22\21\1\152\2\21\2\0\1\7\5\21"+
    "\3\0\1\13\1\0\3\13\2\0\1\7\3\0\1\7"+
    "\1\21\3\0\1\13\15\21\1\153\7\21\2\0\1\7"+
    "\5\21\3\0\1\13\1\0\3\13\2\0\1\7\3\0"+
    "\1\7\1\21\3\0\1\13\16\21\1\154\6\21\2\0"+
    "\1\7\5\21\3\0\1\13\1\0\3\13\2\0\1\7"+
    "\3\0\1\7\1\21\3\0\1\13\10\21\1\155\14\21"+
    "\2\0\1\7\5\21\3\0\1\13\1\0\3\13\2\0"+
    "\1\7\3\0\1\7\1\21\3\0\1\13\25\21\2\0"+
    "\1\7\1\21\1\156\3\21\3\0\1\13\47\0\1\157"+
    "\17\0\1\7\3\0\2\7\4\0\21\7\1\160\3\7"+
    "\2\0\6\7\5\0\3\13\2\0\1\7\3\0\1\7"+
    "\1\21\3\0\1\13\25\21\2\0\1\161\5\21\3\0"+
    "\1\13\1\0\3\13\2\0\1\7\3\0\1\162\1\21"+
    "\3\0\1\13\25\21\2\0\1\7\5\21\3\0\1\13"+
    "\1\0\3\13\2\0\1\7\3\0\1\7\1\21\3\0"+
    "\1\13\14\21\1\163\10\21\2\0\1\7\5\21\3\0"+
    "\1\13\1\0\3\13\2\0\1\7\3\0\1\7\1\21"+
    "\3\0\1\13\15\21\1\164\7\21\2\0\1\7\5\21"+
    "\3\0\1\13\1\0\3\13\2\0\1\7\3\0\1\7"+
    "\1\21\3\0\1\13\17\21\1\165\5\21\2\0\1\7"+
    "\5\21\3\0\1\13\6\0\1\7\3\0\2\7\4\0"+
    "\10\7\1\166\14\7\2\0\6\7\5\0\3\13\2\0"+
    "\1\7\3\0\1\7\1\21\3\0\1\13\4\21\1\167"+
    "\20\21\2\0\1\7\5\21\3\0\1\13\1\0\3\13"+
    "\2\0\1\7\3\0\1\7\1\21\3\0\1\13\4\21"+
    "\1\170\20\21\2\0\1\7\5\21\3\0\1\13\1\0"+
    "\3\13\2\0\1\7\3\0\1\7\1\21\3\0\1\13"+
    "\14\21\1\171\10\21\2\0\1\7\5\21\3\0\1\13"+
    "\1\0\3\13\2\0\1\7\3\0\1\7\1\21\3\0"+
    "\1\13\4\21\1\172\20\21\2\0\1\7\5\21\3\0"+
    "\1\13\1\0\3\13\2\0\1\7\3\0\1\7\1\21"+
    "\3\0\1\13\25\21\2\0\1\173\5\21\3\0\1\13"+
    "\1\0\3\13\2\0\1\7\3\0\1\7\1\21\3\0"+
    "\1\13\15\21\1\174\7\21\2\0\1\7\5\21\3\0"+
    "\1\13\1\0\3\13\2\0\1\7\3\0\1\7\1\21"+
    "\3\0\1\13\1\175\24\21\2\0\1\7\5\21\3\0"+
    "\1\13\1\0\3\13\2\0\1\7\3\0\1\7\1\21"+
    "\3\0\1\13\25\21\2\0\1\7\1\176\4\21\3\0"+
    "\1\13\23\0\1\177\43\0\1\7\3\0\2\7\4\0"+
    "\4\7\1\200\20\7\2\0\6\7\12\0\1\7\3\0"+
    "\2\7\4\0\21\7\1\201\3\7\2\0\6\7\12\0"+
    "\1\7\3\0\2\7\4\0\1\7\1\202\23\7\2\0"+
    "\6\7\5\0\3\13\2\0\1\7\3\0\1\7\1\21"+
    "\3\0\1\13\1\203\24\21\2\0\1\7\5\21\3\0"+
    "\1\13\1\0\3\13\2\0\1\7\3\0\1\7\1\21"+
    "\3\0\1\13\17\21\1\204\5\21\2\0\1\7\5\21"+
    "\3\0\1\13\1\0\3\13\2\0\1\7\3\0\1\7"+
    "\1\21\3\0\1\13\15\21\1\205\7\21\2\0\1\7"+
    "\5\21\3\0\1\13\6\0\1\7\3\0\2\7\4\0"+
    "\23\7\1\206\1\7\2\0\6\7\5\0\3\13\2\0"+
    "\1\7\3\0\1\7\1\21\3\0\1\13\4\21\1\207"+
    "\20\21\2\0\1\7\5\21\3\0\1\13\1\0\3\13"+
    "\2\0\1\7\3\0\1\7\1\21\3\0\1\13\20\21"+
    "\1\210\4\21\2\0\1\7\5\21\3\0\1\13\6\0"+
    "\1\7\3\0\2\7\4\0\23\7\1\211\1\7\2\0"+
    "\6\7\5\0\3\13\2\0\1\7\3\0\1\7\1\21"+
    "\3\0\1\13\20\21\1\212\4\21\2\0\1\7\5\21"+
    "\3\0\1\13\24\0\1\213\42\0\1\7\3\0\2\7"+
    "\4\0\24\7\1\214\2\0\6\7\12\0\1\7\3\0"+
    "\2\7\4\0\4\7\1\215\20\7\2\0\6\7\12\0"+
    "\1\7\3\0\2\7\4\0\15\7\1\216\7\7\2\0"+
    "\6\7\5\0\3\13\2\0\1\7\3\0\1\7\1\21"+
    "\3\0\1\13\20\21\1\217\4\21\2\0\1\7\5\21"+
    "\3\0\1\13\6\0\1\7\3\0\2\7\4\0\10\7"+
    "\1\220\14\7\2\0\6\7\5\0\3\13\2\0\1\7"+
    "\3\0\1\7\1\21\3\0\1\13\20\21\1\221\4\21"+
    "\2\0\1\7\5\21\3\0\1\13\1\0\3\13\2\0"+
    "\1\7\3\0\1\7\1\21\3\0\1\13\21\21\1\222"+
    "\3\21\2\0\1\7\5\21\3\0\1\13\6\0\1\7"+
    "\3\0\2\7\4\0\10\7\1\223\14\7\2\0\6\7"+
    "\53\0\1\224\17\0\1\7\3\0\2\7\4\0\21\7"+
    "\1\225\3\7\2\0\6\7\12\0\1\7\3\0\2\7"+
    "\4\0\24\7\1\226\2\0\6\7\12\0\1\7\3\0"+
    "\2\7\4\0\24\7\1\227\2\0\6\7\12\0\1\7"+
    "\3\0\2\7\4\0\1\230\24\7\2\0\6\7\5\0"+
    "\3\13\2\0\1\7\3\0\1\7\1\21\3\0\1\13"+
    "\1\231\24\21\2\0\1\7\5\21\3\0\1\13\6\0"+
    "\1\7\3\0\2\7\4\0\20\7\1\232\4\7\2\0"+
    "\6\7\27\0\1\233\43\0\1\7\3\0\2\7\4\0"+
    "\15\7\1\234\7\7\2\0\6\7\12\0\1\7\3\0"+
    "\2\7\4\0\21\7\1\235\3\7\2\0\6\7\12\0"+
    "\1\7\3\0\2\7\4\0\10\7\1\236\14\7\2\0"+
    "\6\7\24\0\1\237\46\0\1\7\3\0\2\7\4\0"+
    "\15\7\1\240\7\7\2\0\6\7\12\0\1\7\3\0"+
    "\2\7\4\0\1\7\1\241\23\7\2\0\6\7\45\0"+
    "\1\242\25\0\1\7\3\0\2\7\4\0\12\7\1\243"+
    "\12\7\2\0\6\7\41\0\1\244\31\0\1\7\3\0"+
    "\2\7\4\0\4\7\1\245\20\7\2\0\6\7\44\0"+
    "\1\246\36\0\1\247\42\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[6468];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\1\1\2\11\1\1\3\11\1\1\1\11"+
    "\1\1\2\11\11\1\2\11\1\1\3\11\1\0\21\1"+
    "\1\0\24\1\1\0\24\1\1\0\23\1\1\0\17\1"+
    "\1\0\13\1\1\0\10\1\1\0\6\1\1\0\3\1"+
    "\1\0\2\1\1\0\1\1\1\0\1\1\1\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[167];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    private Symbol symbol(int type){
        return new Symbol(type, yyline +1, yycolumn +1);
    }

    private Symbol symbol(int type, Object value){
        System.out.println("Token con valor reconocido: " + yytext());
        return new Symbol(type, yyline +1, yycolumn + 1, value);
    }

    private void error (String message){
        System.out.println("Error en la linea: " + (yyline +1) + " columna: " + (yycolumn +1) + " : " + message);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LexerTrivias(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
              {
                return symbol(sym.EOF);
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { System.out.println("No se reconocio el lexema " + yytext() + " como un token valido y se ignoro.");
                 //errores.agregarError(yytext(), yyline +1, yycolumn + 1, "Lexico", "El simbolo no se encuentra definido en el alfabeto.");
            }
          // fall through
          case 41: break;
          case 2:
            { /* Ignorar */
            }
          // fall through
          case 42: break;
          case 3:
            { return symbol(sym.EXCLAM);
            }
          // fall through
          case 43: break;
          case 4:
            { return symbol(sym.COMILL);
            }
          // fall through
          case 44: break;
          case 5:
            { return symbol(sym.IDENTIFICADOR, yytext());
            }
          // fall through
          case 45: break;
          case 6:
            { return symbol(sym.PAROPN);
            }
          // fall through
          case 46: break;
          case 7:
            { return symbol(sym.PARCLS);
            }
          // fall through
          case 47: break;
          case 8:
            { return symbol(sym.COMMA);
            }
          // fall through
          case 48: break;
          case 9:
            { return symbol(sym.STRING, yytext());
            }
          // fall through
          case 49: break;
          case 10:
            { return symbol(sym.DOSPUN);
            }
          // fall through
          case 50: break;
          case 11:
            { return symbol(sym.MENQUE);
            }
          // fall through
          case 51: break;
          case 12:
            { return symbol(sym.MAYQUE);
            }
          // fall through
          case 52: break;
          case 13:
            { return symbol(sym.QSTMRK);
            }
          // fall through
          case 53: break;
          case 14:
            { return symbol(sym.COROPN);
            }
          // fall through
          case 54: break;
          case 15:
            { return symbol(sym.CORCLS);
            }
          // fall through
          case 55: break;
          case 16:
            { return symbol(sym.LLAVOP);
            }
          // fall through
          case 56: break;
          case 17:
            { return symbol(sym.ORSYMB);
            }
          // fall through
          case 57: break;
          case 18:
            { return symbol(sym.LLAVCL);
            }
          // fall through
          case 58: break;
          case 19:
            { return symbol(sym.TEMA  );
            }
          // fall through
          case 59: break;
          case 20:
            { return symbol(sym.COMBO  );
            }
          // fall through
          case 60: break;
          case 21:
            { return symbol(sym.FECHA );
            }
          // fall through
          case 61: break;
          case 22:
            { return symbol(sym.PARAM_FIL);
            }
          // fall through
          case 62: break;
          case 23:
            { return symbol(sym.RADIO  );
            }
          // fall through
          case 63: break;
          case 24:
            { return symbol(sym.PARAM_IND);
            }
          // fall through
          case 64: break;
          case 25:
            { return symbol(sym.NOMBRE);
            }
          // fall through
          case 65: break;
          case 26:
            { return symbol(sym.TIEMPO);
            }
          // fall through
          case 66: break;
          case 27:
            { return symbol(sym.PARAM_TRI);
            }
          // fall through
          case 67: break;
          case 28:
            { return symbol(sym.TRIVIA);
            }
          // fall through
          case 68: break;
          case 29:
            { return symbol(sym.CREADO);
            }
          // fall through
          case 69: break;
          case 30:
            { return symbol(sym.FICHERO);
            }
          // fall through
          case 70: break;
          case 31:
            { return symbol(sym.TRIVIAS);
            }
          // fall through
          case 71: break;
          case 32:
            { return symbol(sym.PARAM_COL);
            }
          // fall through
          case 72: break;
          case 33:
            { return symbol(sym.PARAM_OPC);
            }
          // fall through
          case 73: break;
          case 34:
            { // Acción a realizar cuando se encuentra "CHECK-BOX"
        return symbol(sym.CHECKBO);
            }
          // fall through
          case 74: break;
          case 35:
            { return symbol(sym.ID_TRI);
            }
          // fall through
          case 75: break;
          case 36:
            { return symbol(sym.PARAM_RES);
            }
          // fall through
          case 76: break;
          case 37:
            { return symbol(sym.AREA_TE);
            }
          // fall through
          case 77: break;
          case 38:
            { return symbol(sym.CAMPO_T);
            }
          // fall through
          case 78: break;
          case 39:
            { return symbol(sym.PARAM_TEX);
            }
          // fall through
          case 79: break;
          case 40:
            { return symbol(sym.ENCABEZADO);
            }
          // fall through
          case 80: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
