
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.jbrod.servidorprincipal.analizadores.carga.puntuaciones;

import java_cup.runtime.*;
import com.jbrod.servidorprincipal.trivias.Motor;
import com.jbrod.servidorprincipal.trivias.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class ParserPuntuaciones extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public ParserPuntuaciones() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public ParserPuntuaciones(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public ParserPuntuaciones(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\010\000\002\002\004\000\002\002\003\000\002\025" +
    "\003\000\002\025\003\000\002\014\006\000\002\012\004" +
    "\000\002\012\002\000\002\011\032" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\044\000\004\057\005\001\002\000\004\002\000\001" +
    "\002\000\004\021\010\001\002\000\004\002\007\001\002" +
    "\000\004\002\001\001\002\000\006\011\011\022\ufffb\001" +
    "\002\000\004\060\016\001\002\000\006\011\011\022\ufffb" +
    "\001\002\000\004\022\014\001\002\000\004\002\ufffd\001" +
    "\002\000\004\022\ufffc\001\002\000\004\014\017\001\002" +
    "\000\004\006\020\001\002\000\004\012\021\001\002\000" +
    "\004\015\022\001\002\000\004\025\023\001\002\000\004" +
    "\054\024\001\002\000\004\025\025\001\002\000\004\014" +
    "\026\001\002\000\004\006\027\001\002\000\004\023\030" +
    "\001\002\000\004\025\031\001\002\000\004\033\032\001" +
    "\002\000\004\025\033\001\002\000\004\014\034\001\002" +
    "\000\006\006\036\007\035\001\002\000\006\016\ufffe\023" +
    "\ufffe\001\002\000\006\016\uffff\023\uffff\001\002\000\004" +
    "\023\040\001\002\000\004\025\041\001\002\000\004\061" +
    "\042\001\002\000\004\025\043\001\002\000\004\014\044" +
    "\001\002\000\006\006\036\007\035\001\002\000\004\016" +
    "\046\001\002\000\006\011\ufffa\022\ufffa\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\044\000\006\002\005\014\003\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\011\011\012\012\001\001\000\002\001\001\000" +
    "\006\011\011\012\014\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\025" +
    "\036\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\025\044\001\001\000\002" +
    "\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$ParserPuntuaciones$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$ParserPuntuaciones$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$ParserPuntuaciones$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



        
        public String resultado = "";
        private Motor motor; 

        // Conectar el parser al escaner
        public ParserPuntuaciones(LexerPuntuaciones lex, Motor motor){
            super(lex);
            this.motor = motor;
        }

        public void syntax_error(Symbol cur_token){
            System.out.println("Simbolo con error:" + symbl_name_from_id(cur_token.sym));
            System.out.println("Linea " + cur_token.left);
            System.out.println("Columna " + cur_token.right);
            if (expected_token_ids().isEmpty()) {
                System.out.println("Ya no se esperaba ningun simbolo");
                //reporteErrores.agregarError(symbl_name_from_id(cur_token.sym),cur_token.left,cur_token.right, "Sintactico", "Ya no se esperaba ningun simbolo." );
            }else{
                //reporteErrores.agregarError(symbl_name_from_id(cur_token.sym),cur_token.left,cur_token.right, "Sintactico", "Se esperaba otro simbolo." );
            }
        }

        /*public void unrecovered_syntax_error(Symbol cur_token) {
            System.out.println("Error irrecuperable sobrecargado");
        }*/

    private String secureString(Object o){
            if( o != null){
                return o.toString();
            }else{
                return "";
            }
    }

    private int secureInt(Object o){
            String i = secureString(o);
            //System.out.println("A convertir: " + i);
            try{
                int n = Integer.parseInt(i);
                //System.out.println("Convertido: " + n);
                return n;
            }catch(NumberFormatException e){
                //System.out.println("Hubo un error al convertir un numero.");
                return 10;
            }
    }

    private void imprimir(String st){
            System.out.println(st + "\n\n\n\n");
    }

    

/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$ParserPuntuaciones$actions {
  private final ParserPuntuaciones parser;

  /** Constructor */
  CUP$ParserPuntuaciones$actions(ParserPuntuaciones parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$ParserPuntuaciones$do_action_part00000000(
    int                        CUP$ParserPuntuaciones$act_num,
    java_cup.runtime.lr_parser CUP$ParserPuntuaciones$parser,
    java.util.Stack            CUP$ParserPuntuaciones$stack,
    int                        CUP$ParserPuntuaciones$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$ParserPuntuaciones$result;

      /* select the action based on the action number */
      switch (CUP$ParserPuntuaciones$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= inicio EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$ParserPuntuaciones$stack.elementAt(CUP$ParserPuntuaciones$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$ParserPuntuaciones$stack.elementAt(CUP$ParserPuntuaciones$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$ParserPuntuaciones$stack.elementAt(CUP$ParserPuntuaciones$top-1)).value;
		RESULT = start_val;
              CUP$ParserPuntuaciones$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$ParserPuntuaciones$stack.elementAt(CUP$ParserPuntuaciones$top-1)), ((java_cup.runtime.Symbol)CUP$ParserPuntuaciones$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$ParserPuntuaciones$parser.done_parsing();
          return CUP$ParserPuntuaciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // inicio ::= puntuaciones 
            {
              Object RESULT =null;

              CUP$ParserPuntuaciones$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$ParserPuntuaciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPuntuaciones$stack.peek()), RESULT);
            }
          return CUP$ParserPuntuaciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // id_st ::= IDENTIFICADOR 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$ParserPuntuaciones$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$ParserPuntuaciones$stack.peek()).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$ParserPuntuaciones$stack.peek()).value;
		 RESULT = id; 
              CUP$ParserPuntuaciones$result = parser.getSymbolFactory().newSymbol("id_st",19, ((java_cup.runtime.Symbol)CUP$ParserPuntuaciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPuntuaciones$stack.peek()), RESULT);
            }
          return CUP$ParserPuntuaciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // id_st ::= STRING 
            {
              Object RESULT =null;
		int stleft = ((java_cup.runtime.Symbol)CUP$ParserPuntuaciones$stack.peek()).left;
		int stright = ((java_cup.runtime.Symbol)CUP$ParserPuntuaciones$stack.peek()).right;
		Object st = (Object)((java_cup.runtime.Symbol) CUP$ParserPuntuaciones$stack.peek()).value;
		 RESULT = st; 
              CUP$ParserPuntuaciones$result = parser.getSymbolFactory().newSymbol("id_st",19, ((java_cup.runtime.Symbol)CUP$ParserPuntuaciones$stack.peek()), ((java_cup.runtime.Symbol)CUP$ParserPuntuaciones$stack.peek()), RESULT);
            }
          return CUP$ParserPuntuaciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // puntuaciones ::= PUNTUACIONES PAROPN multiples_puntuaciones PARCLS 
            {
              Object RESULT =null;

              CUP$ParserPuntuaciones$result = parser.getSymbolFactory().newSymbol("puntuaciones",10, ((java_cup.runtime.Symbol)CUP$ParserPuntuaciones$stack.elementAt(CUP$ParserPuntuaciones$top-3)), ((java_cup.runtime.Symbol)CUP$ParserPuntuaciones$stack.peek()), RESULT);
            }
          return CUP$ParserPuntuaciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // multiples_puntuaciones ::= puntuacion multiples_puntuaciones 
            {
              Object RESULT =null;

              CUP$ParserPuntuaciones$result = parser.getSymbolFactory().newSymbol("multiples_puntuaciones",8, ((java_cup.runtime.Symbol)CUP$ParserPuntuaciones$stack.elementAt(CUP$ParserPuntuaciones$top-1)), ((java_cup.runtime.Symbol)CUP$ParserPuntuaciones$stack.peek()), RESULT);
            }
          return CUP$ParserPuntuaciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // multiples_puntuaciones ::= 
            {
              Object RESULT =null;

              CUP$ParserPuntuaciones$result = parser.getSymbolFactory().newSymbol("multiples_puntuaciones",8, ((java_cup.runtime.Symbol)CUP$ParserPuntuaciones$stack.peek()), RESULT);
            }
          return CUP$ParserPuntuaciones$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // puntuacion ::= MENQUE PUNTUACION_T DOSPUN IDENTIFICADOR MAYQUE LLAVOP COMILL USUARIO COMILL DOSPUN IDENTIFICADOR COMMA COMILL TIEMPO COMILL DOSPUN id_st COMMA COMILL PUNTEO COMILL DOSPUN id_st LLAVCL 
            {
              Object RESULT =null;
		int trleft = ((java_cup.runtime.Symbol)CUP$ParserPuntuaciones$stack.elementAt(CUP$ParserPuntuaciones$top-20)).left;
		int trright = ((java_cup.runtime.Symbol)CUP$ParserPuntuaciones$stack.elementAt(CUP$ParserPuntuaciones$top-20)).right;
		Object tr = (Object)((java_cup.runtime.Symbol) CUP$ParserPuntuaciones$stack.elementAt(CUP$ParserPuntuaciones$top-20)).value;
		int usleft = ((java_cup.runtime.Symbol)CUP$ParserPuntuaciones$stack.elementAt(CUP$ParserPuntuaciones$top-13)).left;
		int usright = ((java_cup.runtime.Symbol)CUP$ParserPuntuaciones$stack.elementAt(CUP$ParserPuntuaciones$top-13)).right;
		Object us = (Object)((java_cup.runtime.Symbol) CUP$ParserPuntuaciones$stack.elementAt(CUP$ParserPuntuaciones$top-13)).value;
		int tpleft = ((java_cup.runtime.Symbol)CUP$ParserPuntuaciones$stack.elementAt(CUP$ParserPuntuaciones$top-7)).left;
		int tpright = ((java_cup.runtime.Symbol)CUP$ParserPuntuaciones$stack.elementAt(CUP$ParserPuntuaciones$top-7)).right;
		Object tp = (Object)((java_cup.runtime.Symbol) CUP$ParserPuntuaciones$stack.elementAt(CUP$ParserPuntuaciones$top-7)).value;
		int ptleft = ((java_cup.runtime.Symbol)CUP$ParserPuntuaciones$stack.elementAt(CUP$ParserPuntuaciones$top-1)).left;
		int ptright = ((java_cup.runtime.Symbol)CUP$ParserPuntuaciones$stack.elementAt(CUP$ParserPuntuaciones$top-1)).right;
		Object pt = (Object)((java_cup.runtime.Symbol) CUP$ParserPuntuaciones$stack.elementAt(CUP$ParserPuntuaciones$top-1)).value;
		
                            String trivia  = secureString(tr).replaceAll("\\s+", "");;
                            String usuario = secureString(us).replaceAll("\\s+", ""); 
                            Puntuacion p = new Puntuacion(trivia, usuario,secureInt(tp),  secureInt(pt));
                            motor.agregarPuntuacion(p);
                            System.out.println("AGREGAR PUNTUACION DETECTADO:");
                            System.out.println("Usuario: "  + usuario        + "   Trivia: "     + trivia);
                            System.out.println("Tiempo: "   + secureInt(tp)  + "   Puntuacion: " + secureInt(pt));
                    
              CUP$ParserPuntuaciones$result = parser.getSymbolFactory().newSymbol("puntuacion",7, ((java_cup.runtime.Symbol)CUP$ParserPuntuaciones$stack.elementAt(CUP$ParserPuntuaciones$top-23)), ((java_cup.runtime.Symbol)CUP$ParserPuntuaciones$stack.peek()), RESULT);
            }
          return CUP$ParserPuntuaciones$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$ParserPuntuaciones$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$ParserPuntuaciones$do_action(
    int                        CUP$ParserPuntuaciones$act_num,
    java_cup.runtime.lr_parser CUP$ParserPuntuaciones$parser,
    java.util.Stack            CUP$ParserPuntuaciones$stack,
    int                        CUP$ParserPuntuaciones$top)
    throws java.lang.Exception
    {
              return CUP$ParserPuntuaciones$do_action_part00000000(
                               CUP$ParserPuntuaciones$act_num,
                               CUP$ParserPuntuaciones$parser,
                               CUP$ParserPuntuaciones$stack,
                               CUP$ParserPuntuaciones$top);
    }
}

}
