
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.jbrod.servidorprincipal.analizadores.carga.puntuaciones;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 6;
  public static final int MENQUE = 7;
  public static final int PAROPN = 15;
  public static final int QSTMRK = 18;
  public static final int PUNTUACION_T = 46;
  public static final int PARAM_FIL = 39;
  public static final int AREA_TE = 28;
  public static final int NOMBRE = 22;
  public static final int CORCLS = 14;
  public static final int EXCLAM = 9;
  public static final int PARAM_IND = 35;
  public static final int FECHA = 24;
  public static final int ORSYMB = 20;
  public static final int IDENTIFICADOR = 4;
  public static final int TRIVIAS = 33;
  public static final int USUARIO = 42;
  public static final int COMMA = 17;
  public static final int TRIVIA = 3;
  public static final int CAMPO_T = 27;
  public static final int FICHERO = 31;
  public static final int USUARIOS = 41;
  public static final int EOF = 0;
  public static final int LLAVCL = 12;
  public static final int COMILL = 19;
  public static final int PARAM_COL = 40;
  public static final int COROPN = 13;
  public static final int error = 1;
  public static final int LLAVOP = 11;
  public static final int INSTITUC = 44;
  public static final int ENCABEZADO = 2;
  public static final int PARAM_TRI = 34;
  public static final int PUNTUACIONES = 45;
  public static final int PASSWORD = 43;
  public static final int MAYQUE = 8;
  public static final int PARAM_TEX = 36;
  public static final int TEMA = 26;
  public static final int DOSPUN = 10;
  public static final int RADIO = 30;
  public static final int PARCLS = 16;
  public static final int COMBO = 32;
  public static final int ID_TRI = 21;
  public static final int TIEMPO = 25;
  public static final int STRING = 5;
  public static final int CHECKBO = 29;
  public static final int PARAM_OPC = 38;
  public static final int CREADO = 23;
  public static final int PARAM_RES = 37;
  public static final int PUNTEO = 47;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ENCABEZADO",
  "TRIVIA",
  "IDENTIFICADOR",
  "STRING",
  "NUMERO",
  "MENQUE",
  "MAYQUE",
  "EXCLAM",
  "DOSPUN",
  "LLAVOP",
  "LLAVCL",
  "COROPN",
  "CORCLS",
  "PAROPN",
  "PARCLS",
  "COMMA",
  "QSTMRK",
  "COMILL",
  "ORSYMB",
  "ID_TRI",
  "NOMBRE",
  "CREADO",
  "FECHA",
  "TIEMPO",
  "TEMA",
  "CAMPO_T",
  "AREA_TE",
  "CHECKBO",
  "RADIO",
  "FICHERO",
  "COMBO",
  "TRIVIAS",
  "PARAM_TRI",
  "PARAM_IND",
  "PARAM_TEX",
  "PARAM_RES",
  "PARAM_OPC",
  "PARAM_FIL",
  "PARAM_COL",
  "USUARIOS",
  "USUARIO",
  "PASSWORD",
  "INSTITUC",
  "PUNTUACIONES",
  "PUNTUACION_T",
  "PUNTEO"
  };
}

