// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: Lexer.flex

/* - - - - - - - - - - - - - - - - - CODIGO DE USUARIO - - - - - - - - - - - - - - - - - */

package com.jbrod.servidorprincipal.analizadores;
import java_cup.runtime.*;



@SuppressWarnings("fallthrough")
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\25\u0100\1\u0200\11\u0100\1\u0300\17\u0100\1\u0400\u10cf\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\5\1\22\0\1\2\1\3\1\4\1\0\1\5"+
    "\7\0\1\6\1\5\1\7\1\0\1\10\1\11\10\12"+
    "\1\13\1\0\1\14\1\15\1\16\1\17\1\0\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\2\27\1\31\1\32\1\33\1\34\1\35\1\27\1\36"+
    "\1\37\1\40\1\41\1\42\1\43\1\44\1\27\1\45"+
    "\1\46\1\0\1\47\1\0\1\50\1\0\1\20\1\21"+
    "\1\51\1\23\1\52\1\25\1\26\1\27\1\53\2\27"+
    "\1\31\1\32\1\54\1\55\1\35\1\27\1\56\1\57"+
    "\1\40\1\41\1\60\1\43\1\61\1\27\1\45\1\62"+
    "\1\0\1\63\7\0\1\1\32\0\1\1\u01df\0\1\1"+
    "\177\0\13\1\22\0\1\64\12\0\2\1\5\0\1\1"+
    "\57\0\1\1\240\0\1\1\377\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1280];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\17\5\1\14\1\15\1\16"+
    "\1\17\1\0\6\5\1\20\14\5\1\0\30\5\1\0"+
    "\23\5\1\21\4\5\1\0\1\5\1\22\3\5\1\23"+
    "\22\5\1\0\6\5\1\24\3\5\1\25\11\5\1\26"+
    "\3\5\1\0\22\5\1\27\1\5\1\0\1\5\1\30"+
    "\11\5\1\31\1\5\1\32\6\5\1\0\4\5\1\33"+
    "\7\5\1\34\4\5\1\0\20\5\1\0\5\5\1\35"+
    "\13\5\1\0\10\5\1\36\6\5\1\37\1\0\1\5"+
    "\1\40\3\5\1\41\5\5\1\42\2\5\1\0\6\5"+
    "\1\43\4\5\1\0\1\5\1\44\6\5\1\45\1\46"+
    "\1\0\1\5\1\47\1\5\1\50\3\5\1\0\2\5"+
    "\1\51\1\52\1\53\1\0\1\54\1\5\1\0\1\5"+
    "\1\0\1\5\1\0\1\5\1\0\1\5\1\55\1\56";

  private static int [] zzUnpackAction() {
    int [] result = new int[328];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\65\0\152\0\65\0\65\0\237\0\65\0\324"+
    "\0\65\0\u0109\0\65\0\65\0\u013e\0\u0173\0\u01a8\0\u01dd"+
    "\0\u0212\0\u0247\0\u027c\0\u02b1\0\u02e6\0\u031b\0\u0350\0\u0385"+
    "\0\u03ba\0\u03ef\0\u0424\0\65\0\65\0\65\0\65\0\u0459"+
    "\0\u048e\0\u04c3\0\u04f8\0\u052d\0\u0562\0\u0597\0\u05cc\0\u0601"+
    "\0\u0636\0\u066b\0\u06a0\0\u06d5\0\u070a\0\u073f\0\u0774\0\u07a9"+
    "\0\u07de\0\u0813\0\u0848\0\u087d\0\u08b2\0\u08e7\0\u091c\0\u0951"+
    "\0\u0986\0\u09bb\0\u09f0\0\u0a25\0\u0a5a\0\u0a8f\0\u0ac4\0\u0af9"+
    "\0\u0b2e\0\u0b63\0\u0b98\0\u0bcd\0\u0c02\0\u0c37\0\u0c6c\0\u0ca1"+
    "\0\u0cd6\0\u0d0b\0\u0d40\0\u0d75\0\u0daa\0\u0ddf\0\u0e14\0\u0e49"+
    "\0\u0e7e\0\u0eb3\0\u0ee8\0\u0f1d\0\u0f52\0\u0f87\0\u0fbc\0\u0ff1"+
    "\0\u1026\0\u105b\0\u1090\0\u10c5\0\u10fa\0\u112f\0\u1164\0\u1199"+
    "\0\u0173\0\u11ce\0\u1203\0\u1238\0\u126d\0\u12a2\0\u12d7\0\u0173"+
    "\0\u130c\0\u1341\0\u1376\0\u0173\0\u13ab\0\u13e0\0\u1415\0\u144a"+
    "\0\u147f\0\u14b4\0\u14e9\0\u151e\0\u1553\0\u1588\0\u15bd\0\u15f2"+
    "\0\u1627\0\u165c\0\u1691\0\u16c6\0\u16fb\0\u1730\0\u1765\0\u179a"+
    "\0\u17cf\0\u1804\0\u1839\0\u186e\0\u18a3\0\u0173\0\u18d8\0\u190d"+
    "\0\u1942\0\u0173\0\u1977\0\u19ac\0\u19e1\0\u1a16\0\u1a4b\0\u1a80"+
    "\0\u1ab5\0\u1aea\0\u1b1f\0\u0173\0\u1b54\0\u1b89\0\u1bbe\0\u1bf3"+
    "\0\u1c28\0\u1c5d\0\u1c92\0\u1cc7\0\u1cfc\0\u1d31\0\u1d66\0\u1d9b"+
    "\0\u1dd0\0\u1e05\0\u1e3a\0\u1e6f\0\u1ea4\0\u1ed9\0\u1f0e\0\u1f43"+
    "\0\u1f78\0\u1fad\0\u1fe2\0\u2017\0\u204c\0\u2081\0\u0173\0\u20b6"+
    "\0\u20eb\0\u2120\0\u2155\0\u218a\0\u21bf\0\u21f4\0\u2229\0\u225e"+
    "\0\u0173\0\u2293\0\u0173\0\u22c8\0\u22fd\0\u2332\0\u2367\0\u239c"+
    "\0\u23d1\0\u2406\0\u243b\0\u2470\0\u24a5\0\u24da\0\237\0\u250f"+
    "\0\u2544\0\u2579\0\u25ae\0\u25e3\0\u2618\0\u264d\0\u0173\0\u2682"+
    "\0\u26b7\0\u26ec\0\u2721\0\u2756\0\u278b\0\u27c0\0\u27f5\0\u282a"+
    "\0\u285f\0\u2894\0\u28c9\0\u28fe\0\u2933\0\u2968\0\u299d\0\u29d2"+
    "\0\u2a07\0\u2a3c\0\u2a71\0\u2aa6\0\u2adb\0\u2b10\0\u2b45\0\u2b7a"+
    "\0\u2baf\0\u2be4\0\u0173\0\u2c19\0\u2c4e\0\u2c83\0\u2cb8\0\u2ced"+
    "\0\u2d22\0\u2d57\0\u2d8c\0\u2dc1\0\u2df6\0\u2e2b\0\u2e60\0\u2e95"+
    "\0\u2eca\0\u2eff\0\u2f34\0\u2f69\0\u2f9e\0\u2fd3\0\u3008\0\237"+
    "\0\u303d\0\u3072\0\u30a7\0\u30dc\0\u3111\0\u3146\0\237\0\u317b"+
    "\0\u31b0\0\237\0\u31e5\0\u321a\0\u324f\0\237\0\u3284\0\u32b9"+
    "\0\u32ee\0\u3323\0\u3358\0\237\0\u338d\0\u33c2\0\u33f7\0\u342c"+
    "\0\u3461\0\u3496\0\u34cb\0\u3500\0\u3535\0\237\0\u356a\0\u359f"+
    "\0\u35d4\0\u3609\0\u363e\0\u3673\0\237\0\u36a8\0\u36dd\0\u3712"+
    "\0\u3747\0\u377c\0\u37b1\0\237\0\237\0\u37e6\0\u381b\0\237"+
    "\0\u3850\0\237\0\u3885\0\u38ba\0\u38ef\0\u3924\0\u3959\0\u398e"+
    "\0\237\0\237\0\237\0\u39c3\0\237\0\u39f8\0\u3a2d\0\u3a62"+
    "\0\u3a97\0\u3acc\0\u3b01\0\u3b36\0\u3b6b\0\u3ba0\0\65\0\237";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[328];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\4\1\5\1\6\1\7\1\2\3\10"+
    "\1\11\1\12\1\2\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\2\16\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\1\16\1\32\1\33\4\16\1\34"+
    "\1\35\1\6\1\17\1\21\1\23\1\26\1\27\1\31"+
    "\3\16\1\36\1\37\1\2\66\0\2\3\5\0\3\3"+
    "\5\0\26\3\3\0\11\3\10\0\1\6\2\0\3\6"+
    "\5\0\26\6\2\0\12\6\4\0\2\3\5\0\3\10"+
    "\5\0\26\3\3\0\11\3\22\0\1\40\46\0\2\3"+
    "\2\0\1\6\2\0\3\16\5\0\6\16\1\41\17\16"+
    "\2\0\1\6\11\16\4\0\2\3\2\0\1\6\2\0"+
    "\3\16\5\0\26\16\2\0\1\6\11\16\4\0\2\3"+
    "\2\0\1\6\2\0\3\16\5\0\11\16\1\42\2\16"+
    "\1\43\11\16\2\0\1\6\4\16\1\43\4\16\4\0"+
    "\2\3\2\0\1\6\2\0\3\16\5\0\1\44\25\16"+
    "\2\0\1\6\11\16\4\0\2\3\2\0\1\6\2\0"+
    "\3\16\5\0\11\16\1\45\14\16\2\0\1\6\11\16"+
    "\4\0\2\3\2\0\1\6\2\0\3\16\5\0\10\16"+
    "\1\46\15\16\2\0\1\6\2\16\1\46\6\16\4\0"+
    "\2\3\2\0\1\6\2\0\3\16\5\0\3\16\1\47"+
    "\7\16\1\50\12\16\2\0\1\6\3\16\1\50\5\16"+
    "\4\0\2\3\2\0\1\6\2\0\3\16\5\0\14\16"+
    "\1\51\11\16\2\0\1\6\4\16\1\51\4\16\4\0"+
    "\2\3\2\0\1\6\2\0\3\16\5\0\14\16\1\52"+
    "\11\16\2\0\1\6\4\16\1\52\4\16\4\0\2\3"+
    "\2\0\1\6\2\0\3\16\5\0\14\16\1\53\4\16"+
    "\1\54\4\16\2\0\1\6\4\16\1\53\4\16\4\0"+
    "\2\3\2\0\1\6\2\0\3\16\5\0\15\16\1\55"+
    "\10\16\2\0\1\6\11\16\4\0\2\3\2\0\1\6"+
    "\2\0\3\16\5\0\1\56\25\16\2\0\1\6\11\16"+
    "\4\0\2\3\2\0\1\6\2\0\3\16\5\0\4\16"+
    "\1\57\21\16\2\0\1\6\1\16\1\57\7\16\4\0"+
    "\2\3\2\0\1\6\2\0\3\16\5\0\4\16\1\60"+
    "\3\16\1\61\5\16\1\62\7\16\2\0\1\6\1\16"+
    "\1\60\1\61\2\16\1\62\3\16\4\0\2\3\2\0"+
    "\1\6\2\0\3\16\5\0\17\16\1\63\6\16\2\0"+
    "\1\6\6\16\1\63\2\16\64\0\1\64\4\0\2\3"+
    "\2\0\1\6\2\0\3\16\5\0\16\16\1\65\7\16"+
    "\2\0\1\6\5\16\1\65\3\16\4\0\2\3\2\0"+
    "\1\6\2\0\3\16\5\0\1\66\25\16\2\0\1\6"+
    "\11\16\4\0\2\3\2\0\1\6\2\0\3\16\5\0"+
    "\11\16\1\67\14\16\2\0\1\6\11\16\4\0\2\3"+
    "\2\0\1\6\2\0\3\16\5\0\20\16\1\70\5\16"+
    "\2\0\1\6\11\16\4\0\2\3\2\0\1\6\2\0"+
    "\3\16\5\0\10\16\1\71\15\16\2\0\1\6\2\16"+
    "\1\71\6\16\4\0\2\3\2\0\1\6\2\0\3\16"+
    "\5\0\11\16\1\72\1\16\1\73\12\16\2\0\1\6"+
    "\3\16\1\73\5\16\4\0\2\3\2\0\1\6\2\0"+
    "\3\16\5\0\26\16\2\0\1\74\11\16\4\0\2\3"+
    "\2\0\1\6\2\0\3\16\5\0\3\16\1\75\13\16"+
    "\1\76\6\16\2\0\1\6\6\16\1\76\2\16\4\0"+
    "\2\3\2\0\1\6\2\0\3\16\5\0\6\16\1\77"+
    "\17\16\2\0\1\6\11\16\4\0\2\3\2\0\1\6"+
    "\2\0\3\16\5\0\3\16\1\100\22\16\2\0\1\6"+
    "\11\16\4\0\2\3\2\0\1\6\2\0\3\16\5\0"+
    "\12\16\1\101\13\16\2\0\1\6\11\16\4\0\2\3"+
    "\2\0\1\6\2\0\3\16\5\0\4\16\1\102\21\16"+
    "\2\0\1\6\1\16\1\102\7\16\4\0\2\3\2\0"+
    "\1\6\2\0\3\16\5\0\2\16\1\103\23\16\2\0"+
    "\1\6\1\103\10\16\4\0\2\3\2\0\1\6\2\0"+
    "\3\16\5\0\16\16\1\104\1\105\6\16\2\0\1\6"+
    "\5\16\1\104\1\105\2\16\4\0\2\3\2\0\1\6"+
    "\2\0\3\16\5\0\1\106\16\16\1\107\6\16\2\0"+
    "\1\6\6\16\1\107\2\16\4\0\2\3\2\0\1\6"+
    "\2\0\3\16\5\0\12\16\1\110\11\16\1\111\1\16"+
    "\2\0\1\6\10\16\1\111\4\0\2\3\2\0\1\6"+
    "\2\0\3\16\5\0\4\16\1\112\21\16\2\0\1\6"+
    "\1\16\1\112\7\16\4\0\2\3\2\0\1\6\2\0"+
    "\3\16\5\0\10\16\1\113\15\16\2\0\1\6\2\16"+
    "\1\113\6\16\4\0\2\3\2\0\1\6\2\0\3\16"+
    "\5\0\21\16\1\114\4\16\2\0\1\6\11\16\62\0"+
    "\1\115\6\0\2\3\2\0\1\6\2\0\3\16\5\0"+
    "\4\16\1\116\21\16\2\0\1\6\1\16\1\116\7\16"+
    "\4\0\2\3\2\0\1\6\2\0\3\16\5\0\17\16"+
    "\1\117\6\16\2\0\1\6\6\16\1\117\2\16\4\0"+
    "\2\3\2\0\1\6\2\0\3\16\5\0\21\16\1\120"+
    "\4\16\2\0\1\6\11\16\4\0\2\3\2\0\1\6"+
    "\2\0\3\16\5\0\14\16\1\121\11\16\2\0\1\6"+
    "\4\16\1\121\4\16\4\0\2\3\2\0\1\6\2\0"+
    "\3\16\5\0\12\16\1\122\13\16\2\0\1\6\11\16"+
    "\4\0\2\3\2\0\1\6\2\0\3\16\5\0\1\123"+
    "\25\16\2\0\1\6\11\16\4\0\2\3\2\0\1\6"+
    "\2\0\3\16\5\0\26\16\2\0\1\124\11\16\10\0"+
    "\1\6\2\0\3\6\5\0\20\6\1\125\5\6\2\0"+
    "\12\6\4\0\2\3\2\0\1\6\2\0\3\16\5\0"+
    "\10\16\1\126\15\16\2\0\1\6\2\16\1\126\6\16"+
    "\4\0\2\3\2\0\1\6\2\0\3\16\5\0\20\16"+
    "\1\127\5\16\2\0\1\6\11\16\4\0\2\3\2\0"+
    "\1\6\2\0\3\16\5\0\10\16\1\130\15\16\2\0"+
    "\1\6\2\16\1\130\6\16\4\0\2\3\2\0\1\6"+
    "\2\0\3\16\5\0\10\16\1\131\15\16\2\0\1\6"+
    "\2\16\1\131\6\16\4\0\2\3\2\0\1\6\2\0"+
    "\3\16\5\0\1\16\1\132\24\16\2\0\1\6\11\16"+
    "\4\0\2\3\2\0\1\6\2\0\3\16\5\0\22\16"+
    "\1\133\3\16\2\0\1\6\7\16\1\133\1\16\4\0"+
    "\2\3\2\0\1\6\2\0\3\16\5\0\10\16\1\134"+
    "\15\16\2\0\1\6\2\16\1\134\6\16\4\0\2\3"+
    "\2\0\1\6\2\0\3\16\5\0\1\135\25\16\2\0"+
    "\1\6\11\16\4\0\2\3\2\0\1\6\2\0\3\16"+
    "\5\0\17\16\1\136\6\16\2\0\1\6\6\16\1\136"+
    "\2\16\4\0\2\3\2\0\1\6\2\0\3\16\5\0"+
    "\11\16\1\137\14\16\2\0\1\6\11\16\4\0\2\3"+
    "\2\0\1\6\2\0\3\16\5\0\15\16\1\140\10\16"+
    "\2\0\1\6\11\16\4\0\2\3\2\0\1\6\2\0"+
    "\3\16\5\0\1\141\25\16\2\0\1\6\11\16\4\0"+
    "\2\3\2\0\1\6\2\0\3\16\5\0\20\16\1\142"+
    "\5\16\2\0\1\6\11\16\4\0\2\3\2\0\1\6"+
    "\2\0\3\16\5\0\12\16\1\143\13\16\2\0\1\6"+
    "\11\16\4\0\2\3\2\0\1\6\2\0\3\16\5\0"+
    "\22\16\1\144\3\16\2\0\1\6\7\16\1\144\1\16"+
    "\4\0\2\3\2\0\1\6\2\0\3\16\5\0\1\145"+
    "\25\16\2\0\1\6\11\16\60\0\1\146\10\0\2\3"+
    "\2\0\1\6\2\0\3\16\5\0\6\16\1\147\17\16"+
    "\2\0\1\6\11\16\4\0\2\3\2\0\1\6\2\0"+
    "\3\16\5\0\4\16\1\150\21\16\2\0\1\6\1\16"+
    "\1\150\7\16\4\0\2\3\2\0\1\6\2\0\3\16"+
    "\5\0\12\16\1\151\13\16\2\0\1\6\11\16\4\0"+
    "\2\3\2\0\1\6\2\0\3\16\5\0\17\16\1\152"+
    "\6\16\2\0\1\6\6\16\1\152\2\16\4\0\2\3"+
    "\2\0\1\6\2\0\3\16\5\0\10\16\1\153\15\16"+
    "\2\0\1\6\2\16\1\153\6\16\4\0\2\3\2\0"+
    "\1\6\2\0\3\16\5\0\17\16\1\154\6\16\2\0"+
    "\1\6\6\16\1\154\2\16\10\0\1\6\2\0\3\6"+
    "\5\0\17\6\1\155\6\6\2\0\7\6\1\155\2\6"+
    "\10\0\1\6\2\0\3\6\5\0\16\6\1\156\7\6"+
    "\2\0\6\6\1\156\3\6\4\0\2\3\2\0\1\6"+
    "\2\0\3\16\5\0\2\16\1\157\23\16\2\0\1\6"+
    "\1\157\10\16\4\0\2\3\2\0\1\6\2\0\3\16"+
    "\5\0\10\16\1\160\15\16\2\0\1\6\2\16\1\160"+
    "\6\16\4\0\2\3\2\0\1\6\2\0\3\16\5\0"+
    "\13\16\1\161\12\16\2\0\1\6\3\16\1\161\5\16"+
    "\4\0\2\3\2\0\1\6\2\0\3\16\5\0\5\16"+
    "\1\162\20\16\2\0\1\6\11\16\4\0\2\3\2\0"+
    "\1\6\2\0\3\16\5\0\16\16\1\163\7\16\2\0"+
    "\1\6\5\16\1\163\3\16\4\0\2\3\2\0\1\6"+
    "\2\0\3\16\5\0\1\164\13\16\1\165\11\16\2\0"+
    "\1\6\4\16\1\165\4\16\4\0\2\3\2\0\1\6"+
    "\2\0\3\16\5\0\14\16\1\166\11\16\2\0\1\6"+
    "\4\16\1\166\4\16\4\0\2\3\2\0\1\6\2\0"+
    "\3\16\5\0\12\16\1\167\13\16\2\0\1\6\11\16"+
    "\4\0\2\3\2\0\1\6\2\0\3\16\5\0\23\16"+
    "\1\170\2\16\2\0\1\6\11\16\4\0\2\3\2\0"+
    "\1\6\2\0\3\16\5\0\10\16\1\171\15\16\2\0"+
    "\1\6\2\16\1\171\6\16\4\0\2\3\2\0\1\6"+
    "\2\0\3\16\5\0\21\16\1\172\4\16\2\0\1\6"+
    "\11\16\4\0\2\3\2\0\1\6\2\0\3\16\5\0"+
    "\14\16\1\173\11\16\2\0\1\6\4\16\1\173\4\16"+
    "\4\0\2\3\2\0\1\6\2\0\3\16\5\0\15\16"+
    "\1\174\10\16\2\0\1\6\11\16\4\0\2\3\2\0"+
    "\1\6\2\0\3\16\5\0\10\16\1\175\15\16\2\0"+
    "\1\6\2\16\1\175\6\16\4\0\2\3\2\0\1\6"+
    "\2\0\3\16\5\0\16\16\1\176\7\16\2\0\1\6"+
    "\5\16\1\176\3\16\57\0\1\177\11\0\2\3\2\0"+
    "\1\6\2\0\3\16\5\0\1\200\25\16\2\0\1\6"+
    "\11\16\4\0\2\3\2\0\1\6\2\0\3\16\5\0"+
    "\13\16\1\201\12\16\2\0\1\6\3\16\1\201\5\16"+
    "\4\0\2\3\2\0\1\6\2\0\3\16\5\0\26\16"+
    "\2\0\1\202\11\16\4\0\2\3\2\0\1\6\2\0"+
    "\3\16\5\0\13\16\1\203\12\16\2\0\1\6\3\16"+
    "\1\203\5\16\10\0\1\6\2\0\3\6\5\0\14\6"+
    "\1\204\11\6\2\0\5\6\1\204\4\6\10\0\1\6"+
    "\2\0\3\6\5\0\10\6\1\205\15\6\2\0\3\6"+
    "\1\205\6\6\4\0\2\3\2\0\1\6\2\0\3\16"+
    "\5\0\4\16\1\206\21\16\2\0\1\6\1\16\1\206"+
    "\7\16\4\0\2\3\2\0\1\6\2\0\3\16\5\0"+
    "\20\16\1\207\5\16\2\0\1\6\11\16\4\0\2\3"+
    "\2\0\1\6\2\0\3\16\5\0\26\16\2\0\1\210"+
    "\11\16\4\0\2\3\2\0\1\6\2\0\3\16\5\0"+
    "\10\16\1\211\15\16\2\0\1\6\2\16\1\211\6\16"+
    "\4\0\2\3\2\0\1\6\2\0\3\16\5\0\4\16"+
    "\1\212\21\16\2\0\1\6\1\16\1\212\7\16\4\0"+
    "\2\3\2\0\1\6\2\0\3\16\5\0\26\16\2\0"+
    "\1\213\11\16\4\0\2\3\2\0\1\6\2\0\3\16"+
    "\5\0\26\16\2\0\1\214\11\16\4\0\2\3\2\0"+
    "\1\6\2\0\3\16\5\0\13\16\1\215\12\16\2\0"+
    "\1\6\3\16\1\215\5\16\4\0\2\3\2\0\1\6"+
    "\2\0\3\16\5\0\4\16\1\216\21\16\2\0\1\6"+
    "\1\16\1\216\7\16\4\0\2\3\2\0\1\6\2\0"+
    "\3\16\5\0\14\16\1\217\11\16\2\0\1\6\4\16"+
    "\1\217\4\16\4\0\2\3\2\0\1\6\2\0\3\16"+
    "\5\0\25\16\1\220\2\0\1\6\11\16\4\0\2\3"+
    "\2\0\1\6\2\0\3\16\5\0\4\16\1\221\21\16"+
    "\2\0\1\6\1\16\1\221\7\16\4\0\2\3\2\0"+
    "\1\6\2\0\3\16\5\0\26\16\2\0\1\222\11\16"+
    "\4\0\2\3\2\0\1\6\2\0\3\16\5\0\14\16"+
    "\1\223\11\16\2\0\1\6\4\16\1\223\4\16\4\0"+
    "\2\3\2\0\1\6\2\0\3\16\5\0\1\224\25\16"+
    "\2\0\1\6\11\16\4\0\2\3\2\0\1\6\2\0"+
    "\3\16\5\0\10\16\1\225\3\16\1\226\11\16\2\0"+
    "\1\6\2\16\1\227\6\16\5\0\1\230\63\0\2\3"+
    "\2\0\1\6\2\0\3\16\5\0\16\16\1\231\7\16"+
    "\2\0\1\6\5\16\1\231\3\16\4\0\2\3\2\0"+
    "\1\6\2\0\3\16\5\0\1\232\25\16\2\0\1\6"+
    "\11\16\10\0\1\6\2\0\3\6\5\0\21\6\1\233"+
    "\4\6\2\0\12\6\4\0\2\3\2\0\1\6\2\0"+
    "\3\16\5\0\1\234\25\16\2\0\1\6\11\16\10\0"+
    "\1\6\2\0\3\6\5\0\11\6\1\235\14\6\2\0"+
    "\12\6\10\0\1\6\2\0\3\6\5\0\22\6\1\236"+
    "\3\6\2\0\10\6\1\236\1\6\4\0\2\3\2\0"+
    "\1\6\2\0\3\16\5\0\21\16\1\237\4\16\2\0"+
    "\1\6\11\16\10\0\1\6\2\0\3\6\5\0\21\6"+
    "\1\240\4\6\2\0\12\6\4\0\2\3\2\0\1\6"+
    "\2\0\3\16\5\0\2\16\1\241\23\16\2\0\1\6"+
    "\1\241\10\16\10\0\1\6\2\0\3\6\5\0\20\6"+
    "\1\242\5\6\2\0\12\6\10\0\1\6\2\0\3\6"+
    "\5\0\15\6\1\243\10\6\2\0\12\6\4\0\2\3"+
    "\2\0\1\6\2\0\3\16\5\0\4\16\1\244\21\16"+
    "\2\0\1\6\1\16\1\244\7\16\4\0\2\3\2\0"+
    "\1\6\2\0\3\16\5\0\20\16\1\245\5\16\2\0"+
    "\1\6\11\16\4\0\2\3\2\0\1\6\2\0\3\16"+
    "\5\0\16\16\1\246\7\16\2\0\1\6\5\16\1\246"+
    "\3\16\4\0\2\3\2\0\1\6\2\0\3\16\5\0"+
    "\1\247\25\16\2\0\1\6\11\16\4\0\2\3\2\0"+
    "\1\6\2\0\3\16\5\0\17\16\1\250\6\16\2\0"+
    "\1\6\6\16\1\250\2\16\10\0\1\6\2\0\3\6"+
    "\5\0\22\6\1\251\3\6\2\0\10\6\1\251\1\6"+
    "\4\0\2\3\2\0\1\6\2\0\3\16\5\0\26\16"+
    "\2\0\1\252\11\16\4\0\2\3\2\0\1\6\2\0"+
    "\3\16\5\0\14\16\1\253\11\16\2\0\1\6\4\16"+
    "\1\253\4\16\4\0\2\3\2\0\1\6\2\0\3\16"+
    "\5\0\26\16\2\0\1\254\11\16\4\0\2\3\2\0"+
    "\1\6\2\0\3\16\5\0\14\16\1\253\11\16\2\0"+
    "\1\254\4\16\1\253\4\16\63\0\1\255\5\0\2\3"+
    "\2\0\1\6\2\0\3\16\5\0\26\16\2\0\1\256"+
    "\11\16\4\0\2\3\2\0\1\6\2\0\3\16\5\0"+
    "\17\16\1\257\6\16\2\0\1\6\6\16\1\257\2\16"+
    "\10\0\1\6\2\0\3\6\5\0\17\6\1\260\6\6"+
    "\2\0\7\6\1\260\2\6\4\0\2\3\2\0\1\6"+
    "\2\0\3\16\5\0\16\16\1\261\7\16\2\0\1\6"+
    "\5\16\1\261\3\16\10\0\1\6\2\0\3\6\5\0"+
    "\10\6\1\262\15\6\2\0\3\6\1\262\6\6\10\0"+
    "\1\6\2\0\3\6\5\0\10\6\1\263\15\6\2\0"+
    "\3\6\1\263\6\6\4\0\2\3\2\0\1\6\2\0"+
    "\3\16\5\0\2\16\1\264\23\16\2\0\1\6\1\264"+
    "\10\16\10\0\1\6\2\0\3\6\5\0\17\6\1\265"+
    "\6\6\2\0\7\6\1\265\2\6\4\0\2\3\2\0"+
    "\1\6\2\0\3\16\5\0\1\266\25\16\2\0\1\6"+
    "\11\16\10\0\1\6\2\0\3\6\5\0\16\6\1\267"+
    "\7\6\2\0\6\6\1\267\3\6\10\0\1\6\2\0"+
    "\3\6\5\0\1\270\25\6\2\0\12\6\4\0\2\3"+
    "\2\0\1\6\2\0\3\16\5\0\17\16\1\271\6\16"+
    "\2\0\1\6\6\16\1\271\2\16\4\0\2\3\2\0"+
    "\1\6\2\0\3\16\5\0\16\16\1\272\7\16\2\0"+
    "\1\6\5\16\1\272\3\16\4\0\2\3\2\0\1\6"+
    "\2\0\3\16\5\0\3\16\1\273\22\16\2\0\1\6"+
    "\11\16\4\0\2\3\2\0\1\6\2\0\3\16\5\0"+
    "\16\16\1\274\7\16\2\0\1\6\5\16\1\274\3\16"+
    "\4\0\2\3\2\0\1\6\2\0\3\16\5\0\20\16"+
    "\1\275\5\16\2\0\1\6\11\16\10\0\1\6\2\0"+
    "\3\6\5\0\10\6\1\276\15\6\2\0\3\6\1\276"+
    "\6\6\10\0\1\6\2\0\3\6\5\0\15\6\1\277"+
    "\10\6\2\0\12\6\4\0\2\3\2\0\1\6\2\0"+
    "\3\16\5\0\26\16\2\0\1\300\11\16\10\0\1\6"+
    "\2\0\3\6\5\0\13\6\1\301\12\6\2\0\4\6"+
    "\1\301\5\6\55\0\1\302\17\0\1\6\2\0\3\6"+
    "\5\0\2\6\1\303\23\6\2\0\1\6\1\303\10\6"+
    "\10\0\1\6\2\0\3\6\5\0\21\6\1\304\4\6"+
    "\2\0\12\6\4\0\2\3\2\0\1\6\2\0\3\16"+
    "\5\0\26\16\2\0\1\305\11\16\10\0\1\6\2\0"+
    "\3\6\5\0\10\6\1\306\15\6\2\0\1\6\1\306"+
    "\10\6\10\0\1\6\2\0\3\6\5\0\1\307\25\6"+
    "\2\0\12\6\4\0\2\3\2\0\1\6\2\0\3\16"+
    "\5\0\10\16\1\310\15\16\2\0\1\6\2\16\1\310"+
    "\6\16\10\0\1\6\2\0\3\6\5\0\21\6\1\311"+
    "\4\6\2\0\12\6\4\0\2\3\2\0\1\6\2\0"+
    "\3\16\5\0\16\16\1\312\7\16\2\0\1\6\5\16"+
    "\1\312\3\16\10\0\1\6\2\0\3\6\5\0\10\6"+
    "\1\313\15\6\2\0\3\6\1\313\6\6\10\0\1\6"+
    "\2\0\3\6\5\0\17\6\1\314\6\6\2\0\7\6"+
    "\1\314\2\6\4\0\2\3\2\0\1\6\2\0\3\16"+
    "\5\0\14\16\1\315\11\16\2\0\1\6\4\16\1\315"+
    "\4\16\4\0\2\3\2\0\1\6\2\0\3\16\5\0"+
    "\26\16\2\0\1\316\11\16\4\0\2\3\2\0\1\6"+
    "\2\0\3\16\5\0\1\317\25\16\2\0\1\6\11\16"+
    "\10\0\1\6\2\0\3\6\5\0\17\6\1\320\6\6"+
    "\2\0\7\6\1\320\2\6\10\0\1\6\2\0\3\6"+
    "\5\0\16\6\1\321\7\6\2\0\6\6\1\321\3\6"+
    "\10\0\1\6\2\0\3\6\5\0\1\322\25\6\2\0"+
    "\12\6\10\0\1\6\2\0\3\6\5\0\21\6\1\323"+
    "\4\6\2\0\12\6\61\0\1\324\13\0\1\6\2\0"+
    "\3\6\5\0\14\6\1\325\11\6\2\0\5\6\1\325"+
    "\4\6\10\0\1\6\2\0\3\6\5\0\1\326\25\6"+
    "\2\0\12\6\10\0\1\6\2\0\3\6\5\0\20\6"+
    "\1\327\1\330\4\6\2\0\12\6\10\0\1\6\2\0"+
    "\3\6\5\0\10\6\1\331\15\6\2\0\3\6\1\331"+
    "\6\6\4\0\2\3\2\0\1\6\2\0\3\16\5\0"+
    "\14\16\1\332\11\16\2\0\1\6\4\16\1\332\4\16"+
    "\10\0\1\6\2\0\3\6\5\0\1\333\25\6\2\0"+
    "\12\6\4\0\2\3\2\0\1\6\2\0\3\16\5\0"+
    "\26\16\2\0\1\334\11\16\10\0\1\6\2\0\3\6"+
    "\5\0\22\6\1\335\3\6\2\0\10\6\1\335\1\6"+
    "\10\0\1\6\2\0\3\6\5\0\17\6\1\336\6\6"+
    "\2\0\7\6\1\336\2\6\4\0\2\3\2\0\1\6"+
    "\2\0\3\16\5\0\17\16\1\337\6\16\2\0\1\6"+
    "\6\16\1\337\2\16\10\0\1\6\2\0\3\6\5\0"+
    "\17\6\1\340\6\6\2\0\7\6\1\340\2\6\10\0"+
    "\1\6\2\0\3\6\5\0\10\6\1\341\15\6\2\0"+
    "\3\6\1\341\6\6\10\0\1\6\2\0\3\6\5\0"+
    "\4\6\1\342\21\6\2\0\2\6\1\342\7\6\10\0"+
    "\1\6\2\0\3\6\5\0\13\6\1\343\12\6\2\0"+
    "\4\6\1\343\5\6\10\0\1\6\2\0\3\6\5\0"+
    "\4\6\1\344\21\6\2\0\2\6\1\344\7\6\62\0"+
    "\1\345\12\0\1\6\2\0\3\6\5\0\12\6\1\346"+
    "\13\6\2\0\12\6\10\0\1\6\2\0\3\6\5\0"+
    "\16\6\1\347\7\6\2\0\6\6\1\347\3\6\10\0"+
    "\1\6\2\0\3\6\5\0\16\6\1\350\7\6\2\0"+
    "\6\6\1\350\3\6\10\0\1\6\2\0\3\6\5\0"+
    "\17\6\1\351\6\6\2\0\7\6\1\351\2\6\10\0"+
    "\1\6\2\0\3\6\5\0\20\6\1\352\5\6\2\0"+
    "\12\6\4\0\2\3\2\0\1\6\2\0\3\16\5\0"+
    "\13\16\1\353\12\16\2\0\1\6\3\16\1\353\5\16"+
    "\10\0\1\6\2\0\3\6\5\0\16\6\1\354\7\6"+
    "\2\0\6\6\1\354\3\6\10\0\1\6\2\0\3\6"+
    "\5\0\20\6\1\355\1\356\4\6\2\0\12\6\10\0"+
    "\1\6\2\0\3\6\5\0\10\6\1\357\15\6\2\0"+
    "\3\6\1\357\6\6\10\0\1\6\2\0\3\6\5\0"+
    "\23\6\1\360\2\6\2\0\12\6\4\0\2\3\2\0"+
    "\1\6\2\0\3\16\5\0\26\16\2\0\1\361\11\16"+
    "\10\0\1\6\2\0\3\6\5\0\14\6\1\362\11\6"+
    "\2\0\5\6\1\362\4\6\10\0\1\6\2\0\3\6"+
    "\5\0\1\6\1\363\24\6\2\0\12\6\10\0\1\6"+
    "\2\0\3\6\5\0\6\6\1\364\17\6\2\0\12\6"+
    "\10\0\1\6\2\0\3\6\5\0\20\6\1\365\5\6"+
    "\2\0\12\6\10\0\1\6\2\0\3\6\5\0\22\6"+
    "\1\366\3\6\2\0\10\6\1\366\1\6\56\0\1\367"+
    "\16\0\1\6\2\0\3\6\5\0\15\6\1\370\10\6"+
    "\2\0\12\6\10\0\1\6\2\0\3\6\5\0\10\6"+
    "\1\371\15\6\2\0\3\6\1\371\6\6\10\0\1\6"+
    "\2\0\3\6\5\0\10\6\1\372\15\6\2\0\3\6"+
    "\1\372\6\6\10\0\1\6\2\0\3\6\5\0\21\6"+
    "\1\373\4\6\2\0\12\6\10\0\1\6\2\0\3\6"+
    "\5\0\21\6\1\374\4\6\2\0\12\6\10\0\1\6"+
    "\2\0\3\6\5\0\10\6\1\375\15\6\2\0\3\6"+
    "\1\375\6\6\10\0\1\6\2\0\3\6\5\0\16\6"+
    "\1\376\7\6\2\0\6\6\1\376\3\6\10\0\1\6"+
    "\2\0\3\6\5\0\17\6\1\377\6\6\2\0\7\6"+
    "\1\377\2\6\10\0\1\6\2\0\3\6\5\0\1\u0100"+
    "\25\6\2\0\12\6\10\0\1\6\2\0\3\6\5\0"+
    "\14\6\1\u0101\11\6\2\0\5\6\1\u0101\4\6\10\0"+
    "\1\6\2\0\3\6\5\0\20\6\1\u0102\5\6\2\0"+
    "\12\6\10\0\1\6\2\0\3\6\5\0\11\6\1\u0103"+
    "\14\6\2\0\12\6\10\0\1\6\2\0\3\6\5\0"+
    "\11\6\1\u0104\14\6\2\0\12\6\10\0\1\6\2\0"+
    "\3\6\5\0\21\6\1\u0105\4\6\2\0\12\6\10\0"+
    "\1\6\2\0\3\6\5\0\10\6\1\u0106\15\6\2\0"+
    "\3\6\1\u0106\6\6\10\0\1\6\2\0\3\6\5\0"+
    "\14\6\1\u0107\11\6\2\0\5\6\1\u0107\4\6\60\0"+
    "\1\u0108\14\0\1\6\2\0\3\6\5\0\14\6\1\u0109"+
    "\11\6\2\0\5\6\1\u0109\4\6\10\0\1\6\2\0"+
    "\3\6\5\0\14\6\1\u010a\11\6\2\0\5\6\1\u010a"+
    "\4\6\10\0\1\6\2\0\3\6\5\0\22\6\1\u010b"+
    "\3\6\2\0\10\6\1\u010b\1\6\10\0\1\6\2\0"+
    "\3\6\5\0\1\u010c\25\6\2\0\12\6\10\0\1\6"+
    "\2\0\3\6\5\0\3\6\1\u010d\22\6\2\0\12\6"+
    "\10\0\1\6\2\0\3\6\5\0\14\6\1\u010e\11\6"+
    "\2\0\5\6\1\u010e\4\6\10\0\1\6\2\0\3\6"+
    "\5\0\10\6\1\u010f\15\6\2\0\3\6\1\u010f\6\6"+
    "\10\0\1\6\2\0\3\6\5\0\21\6\1\u0110\4\6"+
    "\2\0\12\6\10\0\1\6\2\0\3\6\5\0\16\6"+
    "\1\u0111\7\6\2\0\6\6\1\u0111\3\6\10\0\1\6"+
    "\2\0\3\6\5\0\16\6\1\u0112\7\6\2\0\6\6"+
    "\1\u0112\3\6\10\0\1\6\2\0\3\6\5\0\10\6"+
    "\1\u0113\15\6\2\0\3\6\1\u0113\6\6\10\0\1\6"+
    "\2\0\3\6\5\0\4\6\1\u0114\21\6\2\0\2\6"+
    "\1\u0114\7\6\10\0\1\6\2\0\3\6\5\0\13\6"+
    "\1\u0115\12\6\2\0\4\6\1\u0115\5\6\10\0\1\6"+
    "\2\0\3\6\5\0\6\6\1\u0116\17\6\2\0\12\6"+
    "\57\0\1\u0117\15\0\1\6\2\0\3\6\5\0\13\6"+
    "\1\u0118\12\6\2\0\4\6\1\u0118\5\6\10\0\1\6"+
    "\2\0\3\6\5\0\10\6\1\u0119\15\6\2\0\3\6"+
    "\1\u0119\6\6\10\0\1\6\2\0\3\6\5\0\16\6"+
    "\1\u011a\7\6\2\0\6\6\1\u011a\3\6\10\0\1\6"+
    "\2\0\3\6\5\0\26\6\2\0\1\u011b\11\6\10\0"+
    "\1\6\2\0\3\6\5\0\22\6\1\u011c\3\6\2\0"+
    "\10\6\1\u011c\1\6\10\0\1\6\2\0\3\6\5\0"+
    "\1\u011d\25\6\2\0\12\6\10\0\1\6\2\0\3\6"+
    "\5\0\3\6\1\u011e\22\6\2\0\12\6\10\0\1\6"+
    "\2\0\3\6\5\0\10\6\1\u011f\15\6\2\0\3\6"+
    "\1\u011f\6\6\10\0\1\6\2\0\3\6\5\0\10\6"+
    "\1\u0120\15\6\2\0\1\6\1\u0120\10\6\10\0\1\6"+
    "\2\0\3\6\5\0\20\6\1\u0121\5\6\2\0\12\6"+
    "\10\0\1\6\2\0\3\6\5\0\21\6\1\u0122\4\6"+
    "\2\0\12\6\20\0\1\u0123\54\0\1\6\2\0\3\6"+
    "\5\0\4\6\1\u0124\21\6\2\0\2\6\1\u0124\7\6"+
    "\10\0\1\6\2\0\3\6\5\0\1\u0125\25\6\2\0"+
    "\12\6\10\0\1\6\2\0\3\6\5\0\10\6\1\u0126"+
    "\15\6\2\0\3\6\1\u0126\6\6\10\0\1\6\2\0"+
    "\3\6\5\0\16\6\1\u0127\7\6\2\0\6\6\1\u0127"+
    "\3\6\10\0\1\6\2\0\3\6\5\0\10\6\1\u0128"+
    "\15\6\2\0\3\6\1\u0128\6\6\10\0\1\6\2\0"+
    "\3\6\5\0\16\6\1\u0129\7\6\2\0\6\6\1\u0129"+
    "\3\6\10\0\1\6\2\0\3\6\5\0\22\6\1\u012a"+
    "\3\6\2\0\10\6\1\u012a\1\6\10\0\1\6\2\0"+
    "\3\6\5\0\20\6\1\u012b\5\6\2\0\12\6\10\0"+
    "\1\6\2\0\3\6\5\0\1\u012c\25\6\2\0\12\6"+
    "\10\0\1\6\2\0\3\6\5\0\14\6\1\u012d\11\6"+
    "\2\0\5\6\1\u012d\4\6\67\0\1\u012e\5\0\1\6"+
    "\2\0\3\6\5\0\13\6\1\u012f\12\6\2\0\4\6"+
    "\1\u012f\5\6\10\0\1\6\2\0\3\6\5\0\14\6"+
    "\1\u0130\11\6\2\0\5\6\1\u0130\4\6\10\0\1\6"+
    "\2\0\3\6\5\0\4\6\1\u0131\21\6\2\0\2\6"+
    "\1\u0131\7\6\10\0\1\6\2\0\3\6\5\0\1\u0132"+
    "\25\6\2\0\12\6\10\0\1\6\2\0\3\6\5\0"+
    "\10\6\1\u0133\15\6\2\0\3\6\1\u0133\6\6\10\0"+
    "\1\6\2\0\3\6\5\0\10\6\1\u0134\15\6\2\0"+
    "\3\6\1\u0134\6\6\10\0\1\6\2\0\3\6\5\0"+
    "\21\6\1\u0135\4\6\2\0\12\6\14\0\1\u0136\60\0"+
    "\1\6\2\0\3\6\5\0\20\6\1\u0137\5\6\2\0"+
    "\12\6\10\0\1\6\2\0\3\6\5\0\1\u0138\25\6"+
    "\2\0\12\6\10\0\1\6\2\0\3\6\5\0\14\6"+
    "\1\u0139\11\6\2\0\5\6\1\u0139\4\6\10\0\1\6"+
    "\2\0\3\6\5\0\1\u013a\25\6\2\0\12\6\10\0"+
    "\1\6\2\0\3\6\5\0\3\6\1\u013b\22\6\2\0"+
    "\12\6\12\0\1\u013c\62\0\1\6\2\0\3\6\5\0"+
    "\4\6\1\u013d\21\6\2\0\2\6\1\u013d\7\6\10\0"+
    "\1\6\2\0\3\6\5\0\11\6\1\u013e\14\6\2\0"+
    "\12\6\13\0\1\u013f\61\0\1\6\2\0\3\6\5\0"+
    "\10\6\1\u0140\15\6\2\0\3\6\1\u0140\6\6\67\0"+
    "\1\u0141\5\0\1\6\2\0\3\6\5\0\25\6\1\u0142"+
    "\2\0\12\6\5\0\1\u0143\67\0\1\6\2\0\3\6"+
    "\5\0\1\u0144\25\6\2\0\12\6\22\0\1\u0145\52\0"+
    "\1\6\2\0\3\6\5\0\3\6\1\u0146\22\6\2\0"+
    "\12\6\21\0\1\u0147\53\0\1\6\2\0\3\6\5\0"+
    "\1\u0148\25\6\2\0\12\6\3\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[15317];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\2\11\1\1\1\11\1\1\1\11"+
    "\1\1\2\11\17\1\4\11\1\0\23\1\1\0\30\1"+
    "\1\0\30\1\1\0\30\1\1\0\30\1\1\0\24\1"+
    "\1\0\24\1\1\0\21\1\1\0\20\1\1\0\21\1"+
    "\1\0\20\1\1\0\16\1\1\0\13\1\1\0\12\1"+
    "\1\0\7\1\1\0\5\1\1\0\2\1\1\0\1\1"+
    "\1\0\1\1\1\0\1\1\1\0\1\1\1\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[328];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */

    private Symbol symbol(int type){
        return new Symbol(type, yyline +1, yycolumn +1);
    }

    private Symbol(type, value){
        System.out.println("Token reconocido: " + yytext());
        return new Symbol(type, yyline +1, yycolumn + 1, value);
    }

    private void error (String message){
        System.out.println("Error en la linea: " + (yyline +1) + " columna: " + (yycolumn +1) + " : " + message);
    }



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
              {
                return symbol(sym.EOF);
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { System.out.println("No se reconocio el lexema " + yytext() + " como un token valido y se ignoro.");
                 errores.agregarError(yytext(), yyline +1, yycolumn + 1, "Lexico", "El simbolo no se encuentra definido en el alfabeto.");
            }
          // fall through
          case 47: break;
          case 2:
            { return symbol(sym.STRING, yytext());
            }
          // fall through
          case 48: break;
          case 3:
            { return symbol(sym.EXCLAM);
            }
          // fall through
          case 49: break;
          case 4:
            { return symbol(sym.COMILL);
            }
          // fall through
          case 50: break;
          case 5:
            { return symbol(sym.IDENTIFICADOR, yytexyt());
            }
          // fall through
          case 51: break;
          case 6:
            { return symbol(sym.COMMA);
            }
          // fall through
          case 52: break;
          case 7:
            { return symbol(sym.NUMERO       , Integer.parseInt(yytext()));
            }
          // fall through
          case 53: break;
          case 8:
            { return symbol(sym.DOSPUN);
            }
          // fall through
          case 54: break;
          case 9:
            { return symbol(sym.MENQUE);
            }
          // fall through
          case 55: break;
          case 10:
            { return symbol(sym.MAYQUE);
            }
          // fall through
          case 56: break;
          case 11:
            { return symbol(sym.QSTMRK);
            }
          // fall through
          case 57: break;
          case 12:
            { return symbol(sym.COROPN);
            }
          // fall through
          case 58: break;
          case 13:
            { return symbol(sym.CORCLS);
            }
          // fall through
          case 59: break;
          case 14:
            { return symbol(sym.LLAVOP);
            }
          // fall through
          case 60: break;
          case 15:
            { return symbol(sym.LLAVCL);
            }
          // fall through
          case 61: break;
          case 16:
            { return symbol(sym.ID);
            }
          // fall through
          case 62: break;
          case 17:
            { return symbol(sym.TEMA);
            }
          // fall through
          case 63: break;
          case 18:
            { return symbol(sym.CLASE);
            }
          // fall through
          case 64: break;
          case 19:
            { return symbol(sym.FILAS);
            }
          // fall through
          case 65: break;
          case 20:
            { return symbol(sym.INDICE);
            }
          // fall through
          case 66: break;
          case 21:
            { return symbol(sym.NOMBRE);
            }
          // fall through
          case 67: break;
          case 22:
            { return symbol(sym.TRIVIA);
            }
          // fall through
          case 68: break;
          case 23:
            { return symbol(sym.USUARIO);
            }
          // fall through
          case 69: break;
          case 24:
            { return symbol(sym.COLUMNAS);
            }
          // fall through
          case 70: break;
          case 25:
            { return symbol(sym.OPCIONES);
            }
          // fall through
          case 71: break;
          case 26:
            { return symbol(sym.PASSWORD);
            }
          // fall through
          case 72: break;
          case 27:
            { return symbol(sym.ID_TRIVIA);
            }
          // fall through
          case 73: break;
          case 28:
            { return symbol(sym.RESPUESTA);
            }
          // fall through
          case 74: break;
          case 29:
            { return symbol(sym.INSTITUCION);
            }
          // fall through
          case 75: break;
          case 30:
            { return symbol(sym.NUEVA_TRIVIA);
            }
          // fall through
          case 76: break;
          case 31:
            { return symbol(sym.USUARIO_NUEV);
            }
          // fall through
          case 77: break;
          case 32:
            { return symbol(sym.DATOS_USUARI);
            }
          // fall through
          case 78: break;
          case 33:
            { return symbol(sym.LOGIN_USUARI);
            }
          // fall through
          case 79: break;
          case 34:
            { return symbol(sym.TEXTO_VISIBL);
            }
          // fall through
          case 80: break;
          case 35:
            { return symbol(sym.NUEVO_PASSWO);
            }
          // fall through
          case 81: break;
          case 36:
            { return symbol(sym.ELIMINAR_TRI);
            }
          // fall through
          case 82: break;
          case 37:
            { return symbol(sym.TIEMPO_PREGU);
            }
          // fall through
          case 83: break;
          case 38:
            { return symbol(sym.USUA_ANTIGUO);
            }
          // fall through
          case 84: break;
          case 39:
            { return symbol(sym.ELIMINAR_USU);
            }
          // fall through
          case 85: break;
          case 40:
            { return symbol(sym.MODIF_TRIVIA);
            }
          // fall through
          case 86: break;
          case 41:
            { return symbol(sym.MODI_USUARIO);
            }
          // fall through
          case 87: break;
          case 42:
            { return symbol(sym.PARAM_TRIVIA);
            }
          // fall through
          case 88: break;
          case 43:
            { return symbol(sym.REALIZAR_SOL);
            }
          // fall through
          case 89: break;
          case 44:
            { return symbol(sym.AGREGAR_COMP);
            }
          // fall through
          case 90: break;
          case 45:
            { return symbol(sym.ENCABEZADO);
            }
          // fall through
          case 91: break;
          case 46:
            { return symbol(sym.FIN_SOL_REAL);
            }
          // fall through
          case 92: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
